### ISSUE TITLE
TS33 - Testes de Usabilidade

### ISSUE THREAD

**Issue by gabiMSilva** [fga-eps-mds/2020.1-Grupo4#101]
# TS33 - Testes de Usabilidade

## Descrição

Realizar testes de usabilidade com, pelo menos, 2 usuários em potencial (que podem se tornar usuários reais).

## Critérios de Aceitação

- [x] Fazer teste com pelo menos 2 usuários
- [x] Criar script de teste que será usado em para todos os usuários
- [x] Documentar resultados obtidos e adicionar na wiki.

**Comment by estevaoreis25** [comment]
Esses novos testes de usabilidade devem ficar na mesma pasta dos testes anteriores? Como será feito um novo script eu fiquei com essa dúvida

**Comment by GeovanaRamos** [comment]
> Esses novos testes de usabilidade devem ficar na mesma pasta dos testes anteriores? Como será feito um novo script eu fiquei com essa dúvida

Faz assim:
- Chama o que já ta lá de **1º** Teste de Usabilidade
- Adiciona o seu em uma nova entrada na nav como **2º** Teste de Usabilidade
- Dentro dele segue o mesmo estilo do outro: Introdução, Relatório 1 ..... etc
- Não tem problema vc mudar a forma de documentar, se ela for melhor
