### ISSUE TITLE
TS35 - Otimização das Métricas de Qualidade

### ISSUE THREAD

**Issue by gabiMSilva** [fga-eps-mds/2020.1-Grupo4#103]
# TS35 - Otimização das Métricas de Qualidade

## Descrição

Melhorar as métricas de qualidade presentes no Sonar e CodeClimate, além de corrigir issue já apontadas por essas ferramentas. O único valor que não deve ser melhorado é a cobertura de testes, pois será feita na issue #102.

## Critérios de Aceitação (se aplicável)

- [ ] Melhorar notas de avaliação do código estático
- [ ] Corrigir issues apontadas pelo Code Climate e Sonar
- [ ] Caso algum problema não seja corrigido, informar nessa issue o motivo.

**Comment by peHaick** [comment]
Sobre o SonarCloud: Muitos dos code smells tem relação com variáveis e afins sendo declaradas 2 vezes (Uma na importação e outra como parâmetro para o componente). Porém quando eu tiro um desses 2 para não ficar repetido, a funcionalidade é perdida. Tem algo a se fazer sobre isso?

**Comment by gabiMSilva** [comment]
> Sobre o SonarCloud: Muitos dos code smells tem relação com variáveis e afins sendo declaradas 2 vezes (Uma na importação e outra como parâmetro para o componente). Porém quando eu tiro um desses 2 para não ficar repetido, a funcionalidade é perdida. Tem algo a se fazer sobre isso?

@peHaick Isso é realmente estranho. Quando você importa não precisa colocar no componente. Caso sejam variáveis que possuam conteúdos diferentes, você pode trocar o nome da que vem na importação.

ex.: 

```js

import { Componente as ComponenteDois } from 'path/componente'

const QualquerCoisa = ({Componente}) => {
   [...]
}

```

Nesse caso vão existir dois valores, um que vem nos props e outro importado. Caso vc queira apenas o do import não precisa colocar dentro do componente. Ficaria:

```js

import { Componente } from 'path/componente'

const QualquerCoisa = () => {
   [...]
}

```

**Comment by peHaick** [comment]
O SonarCloud tá apontando 5.8% de duplicação. Olhei aqui e é tudo relacionado aos testes (mais especificamente com a inicialização deles, que é igual). Como não é algo que tenha muito a se fazer, já que imagino que não tenha outro jeito de inicializar os testes, e os testes fazem parte de outra issue, acham que eu deva mexer nisso?

**Comment by GeovanaRamos** [comment]
> O SonarCloud tá apontando 5.8% de duplicação. Olhei aqui e é tudo relacionado aos testes (mais especificamente com a inicialização deles, que é igual). Como não é algo que tenha muito a se fazer, já que imagino que não tenha outro jeito de inicializar os testes, e os testes fazem parte de outra issue, acham que eu deva mexer nisso?

Pode deixar.
