### ISSUE TITLE
TS38 - Arquivo de Apresentação da R2

### ISSUE THREAD

**Issue by gabiMSilva** [fga-eps-mds/2020.1-Grupo4#106]

**Comment by Rocsantos** [comment]
Como iremos começar a organizar isso?

**Comment by GeovanaRamos** [comment]
Slide -> https://docs.google.com/presentation/d/1GaOcdOhQB87c7rmzeHiSj4vBGiYQKL6rRR8t8SxBoR4/edit#slide=id.p (ainda é apenas a cópia da R1)

Roteiro -> https://docs.google.com/document/d/1fANCJiimTfI0W7D08c11bzXFV--EgqLHZtWWACRYfB0/edit 

Vamos trabalhar em cima do roteiro e quem fala o que, depois vamos montando o slide colaborativamente. O mais importante é definir o que cada um vai falar. Fiquem a vontade para acrescentar coisas que acham importante pra vocês como alunos de MDS.
