### ISSUE TITLE
TS06 - Configurar plataformas de comunicação

### ISSUE THREAD

**Issue by gabiMSilva** [fga-eps-mds/2020.1-Grupo4#11]
# TS06 - Configurar plataformas de comunicação

## Descrição
Pesquisar e configurar melhores plataformas/tecnologias para interação do time e realização das prática do Scrum.

## Critérios de Aceitação

- [x] Configurar plataforma de realização da daily
- [x] Configurar plataforma para compartilhamento de documentos e arquivos
- [x] Configurar meio de comunicação para interação entre MDS e EPS 
- [x] Configurar meio de comunicação para revisão e planejamento das sprints
   - [x] Configurar aplicação para realização do Planning Poker

**Comment by GeovanaRamos** [comment]
As ferramentas utilizadas foram:
- Slack para comunicação geral, com canais bem definidos.
- Friday para daily no Slack. Ouve problema com um membro mas contatei o suporte e foi resolvido. 
- Teams para a reunião, preparativos e gravações.
- Planning Poker Online como aba no Teams.
- Google Drive para compartilhamento de arquivos e Iframe na wiki.

Houve uma tentativa de integrar tudo no teams porém por ser da organização UnB houve problemas para aderir aos bots.
