### ISSUE TITLE
TS07 - Elaborar Documento de Arquitetura

### ISSUE THREAD

**Issue by gabiMSilva** [fga-eps-mds/2020.1-Grupo4#13]
# TS07 - Elaborar Documento de Arquitetura

## Descrição

Escrever documento de arquitetura que descreva a arquitetura MERN (Mongo Express, React e Node)

### Tópicos
- [ ] Introdução
- [ ] Representação Arquitetural (imagem e explicação)
- [ ] Metas e Restrições da Arquitetura
- [ ] Tamanho e Desempenho

**Comment by gabiMSilva** [comment]
Utilizar modelo que está nos arquivos do teams

**Comment by EduardoPicolo** [comment]
É pra fazer só os tópicos listados na issue ou o documento todo?

**Comment by gabiMSilva** [comment]
Apenas esses e seus subtópicos por enquanto

**Comment by estevaoreis25** [comment]
Os critérios de aceitação foram modificados? Tive a impressão de que no inicio da semana eram 5 critérios

**Comment by gabiMSilva** [comment]
> Os critérios de aceitação foram modificados? Tive a impressão de que no inicio da semana eram 5 critérios

Sim, removi o de Qualidade pois ficaria redudante com os tópicos da Especificação Suplementar

**Comment by gabiMSilva** [comment]
# Sobre o React

- Utilizaremos os **Reacts Hooks** da nova versão do React (funcional)

- Aplicaremos o **Redux** para gerenciamento estado que precisam ser compartilhados

## Links úteis

- [Conceitos de Redux](https://redux.js.org/tutorials/essentials/part-1-overview-concepts) - possui imagens bem intuitivas que podem ser colocadas no documento
- [React Hooks](https://pt-br.reactjs.org/docs/hooks-intro.html)
