### ISSUE TITLE
TS08 - Elaborar Especificação Suplementar

### ISSUE THREAD

**Issue by gabiMSilva** [fga-eps-mds/2020.1-Grupo4#14]
# TS08 - Elaborar Especificação Suplementar

## Descrição

Escrever Especificação Suplementar de acordo com as funcionalidades e Requisitos do Cliente/Usuário

## Critérios de Aceitação

- Adicionar na Wiki
- Descrever Requisitos não funcionais

**Comment by luucas-melo** [comment]
Qual arquitetura iremos utilizar mesmo?

**Comment by gabiMSilva** [comment]
> Qual arquitetura iremos utilizar mesmo?

Vcs vão usar a stack MERN (Mongo Express + React + Node). Mas se quiser mais detalhes pode falar com os meninos que estão responsáveis pelo [documento de arquitetura](https://github.com/fga-eps-mds/2020.1-Grupo4/issues/13)
