### ISSUE TITLE
TS09 - Desenvolver protótipo de baixa fidelidade

### ISSUE THREAD

**Issue by gabiMSilva** [fga-eps-mds/2020.1-Grupo4#15]
# TS09 - Desenvolver protótipo de baixa fidelidade

## Descrição

Desenvolver desenho das telas e funcionalidade da aplicação

## Critérios de Aceitação

- [ ] Todas as histórias de usuários do backlog devem estar representadas no protótipo

**Comment by gabiMSilva** [comment]
Sugestão: [Bolsamiq](https://balsamiq.com/)

**Comment by Rocsantos** [comment]
Quais são as informações necessárias para o cadastro? Pode-se cadastrar diretamente como mentora? Se sim, terá alguma restrição para fazer o cadastro como mentor, como por exemplo, upar certificado de conhecimento de Django?

**Comment by gabiMSilva** [comment]
@Rocsantos , alguns pontos:

- apesar do aprendiz só poder ser aqueles que se indentificam como do gênero feminino, qualquer pessoa pode ser monitor.
- Para ser monitor a pessoa precisa
   - ter 3 respostas marcadas como solução no fórum ou
   - ter concluído o curso (mulheres)
- No cadastro de uma aprendiz, ela deve dizer se deseja um monitor
- No caso do cadastro de monitor(a), é importante ter a informação se deseja prestar monitoria ou apenas auxiliar no fórum

Por enquanto é isso que me lembro

**Comment by Rocsantos** [comment]
Certo entendi...
A ideia de um cadastro padrão, para interação no fórum, que possa ser atualizado e restringindo, quando entrar no tutorial para aprendiz ou mentor no site, seria válida?

**Comment by gabiMSilva** [comment]
Bom, isso tem que ser pensado na forma que vcs irão desenvolver. 
É importante saber que tipo de usuário ele quer ser já no cadastro por causa das restrições de acesso ao tutorial e à monitoria.
Vocês também devem verificar se o usuário que deseja ser monitor tem os requisitos para isso.

Apesar dessas restrições, vocês devem conversar entre vocês e decidirem qual a melhor forma de implementar.
