### ISSUE TITLE
TS10 - Preparar ambiente de desenvolvimento frontend

### ISSUE THREAD

**Issue by gabiMSilva** [fga-eps-mds/2020.1-Grupo4#16]
# TS10 - Preparar ambiente de desenvolvimento frontend

## Descrição

Preparar e configurar o repositório para o time de MDS começar a desenvolver

## Critérios de Aceitação

- Reproduzir estrutura que será demonstrada no diagrama de pastas 

- Conteinerizar projeto (Docker) 

- Fazer README 

   - Descrição

   - Como rodar o projeto? 

   - Link para Wiki 

   - Equipe

**Comment by GeovanaRamos** [comment]
Vou finalizar o backend antes de avaliar o PR pra podermos testar a rede docker entre os repositórios.
