### ISSUE TITLE
TS12 - Criar template de issues e PRs

### ISSUE THREAD

**Issue by gabiMSilva** [fga-eps-mds/2020.1-Grupo4#18]
# TS12 - Criar template de issues e PRs

## Descrição

Criar modelo de issue e Pull Request automático do Git

## Critérios de Aceitação

- As issues devem possuir ao menos: 

   - Descrição do problema 

   - Possível solução (se aplicável)

   - Critérios de Aceitação

- Os PRs devem possuir ao menos: 

   - Descrição 

   - Como isso foi testado?

   - Imagens (se aplicável) 

   - Essa modificação exige atualização da documentação?

   - Tipo de alteração  

      - Nova feature 

      - Correção de bugs  

      - Alteração de uma funcionalidade

**Comment by GeovanaRamos** [comment]
Acho interessante acrescentar um campo no PR que pergunta que se exige mudança na documentação. Assim a documentação evolui sempre com o código, caso o código resulte em mudanças no que já foi documentado.
