### ISSUE TITLE
Estudar tecnologias

### ISSUE THREAD

**Issue by gabiMSilva** [fga-eps-mds/2020.1-Grupo4#2]
# Estudar tecnologias

## Descrição
Fazer estudo inicial das tecnologias que serão usadas na disciplina

## Critérios de aceitação
- [x] Estudar git 
  - [x] Branch
  - [x] Rebase
  - [x] Merge
- [x] Estudar GitHub 
  - [x] Pull Requests
  - [x] Issues
- [x] Estudar NodeJS
- [x] Estudar ReactJS
- [x] Estudar Testes Unitários

**Comment by luucas-melo** [comment]
Estudei branch, rebase e merge. Além disso estudei um pouco de React e Node, não tive muitas dificuldades, só um pouco em Node. Gostaria de saber se vamos aprender e utilizar docker, pois não sei nada sobre.

**Comment by peHaick** [comment]
Estudei Git e GitHub, revisei um pouco de JavaScript e iniciei Node e React. Não tive muita dificuldade no geral.

**Comment by EduardoPicolo** [comment]
Revisei Node e React, estudei sobre rebase. Sem dificuldades

**Comment by GeovanaRamos** [comment]
> Gostaria de saber se vamos aprender e utilizar docker, pois não sei nada sobre.

Vocês não irão precisar configurar, mas irão utilizar. Não é necessário que estudem a fundo em um primeiro momento. Iremos passar o conhecimento necessário para utilizar ele. Vão precisar apenas instalar e rodar os comandos que já estarão prontos.

**Comment by estevaoreis25** [comment]
Estudei uma introdução das tecnologias Node e React, revisei alguns conhecimentos de git e estudei um pouco sobre documento de visão. Tive um pouco de dificuldade principalmente em Node, já que nunca tive nenhum contato antes, tive dificuldades para interpretar e aplicar os conhecimentos do documento de visão, disponibilizados pela IBM, no documento de visão do projeto. Gostaria ainda de aprender como utilizar o Docker e entender a importância dele no processo de desenvolvimento de software.

**Comment by gabiMSilva** [comment]
@estevaoreis25 No começo é assim mesmo, não se preocupe. 

Nós iremos ensinar o conceito de Docker e os comandos iniciais. Mas depois vcs podem ir atrás de ter um conhecimento mais aprofundado :smile:

**Comment by Rocsantos** [comment]
Estudos feitos:
- git (branches, rebase e merge), foi tudo bem por aqui
- github (pull request e issues), tudo bem também
- nodeJs (já havia trabalhado com esta tecnologia na matéria de Desenvolvimento de Software, apenas revisei algumas coisas)
- reactJs, meio complicado ainda, mas to progredindo.

Ainda sinto dificuldades na parte de mesclar o JS com html, mas to começando a pegar o jeito.

**Comment by JaimeJuan11** [comment]
Reviseis os conhecimentos em git e github tendo em vista que eram conteudos conhecidos, porém estavam caindo em esquecimento. Sobre o Node, React e Mongo; estudei por cima e comprarei um curso para aprofundar o conhecimento.
