### ISSUE TITLE
TS13 - Protótipo de Alta fidelidade

### ISSUE THREAD

**Issue by gabiMSilva** [fga-eps-mds/2020.1-Grupo4#25]
# TS13 - Protótipo de Alta fidelidade

## Descrição

Desenvolver um protótipo de alta fidelidade em um plataforma de prototipação.
Sugestão de ferramenta: [Figma](https://www.figma.com/)

## Solução

Desenhar todas as telas da aplicação de forma realista já considerando paleta de cores e logotipo do projeto.

## Critérios de Aceitação

- [ ] Adicionar à Wiki
- [ ] O protótipo deve representar exatamente o que será implementado
- [ ] Proporcionar melhorias ao protótipo de baixa fidelidade

**Comment by GeovanaRamos** [comment]
De acordo com o [protótipo](https://www.figma.com/file/RxGKd0i4iRzTrRkj8wsVuo/Prototipo-de-alta-fidelidade?node-id=26%3A101) preliminar, as solicitações de alterações são:
- [ ] Trocar a cor principal pelo que foi definido pelo grupo
- [ ] Adicionar a logo 
- [ ] Certificados também deveria estar no dropdown do usuário. Na nav não pois não é uma feature de acesso frequente.
- [ ] A dashboard deveria ser o primeiro link da navbar como "Dashboard"
- [ ] Continuar tutorial pode ser somente Tutorial
- [ ] Os fóruns são para cada módulo. Proponham uma forma disso ficar claro no design. O fórum em si está ótimo, nao precisa mudar, so adequar onde ele se encaixa dentro do site.
- [ ] O tutorial ta com a navegação um pouco dificil. Seria interessante adicionar umas setas <Anterior> <Proximo> ou mudar a seleção navegação entre módulos.
- [ ] Antes das atividades no lado esquerdo do tutorial, deveria ter o link pro texto daquele modulo em si. Para caso esteja em uma atividade e queira retornar ao conteúdo.
- [ ] O modelo de chat usado é mais difícil de implementar. Pensem se irão manter, mas não é obrigatório fazer a troca.

**Comment by EduardoPicolo** [comment]
> De acordo com o [protótipo](https://www.figma.com/file/RxGKd0i4iRzTrRkj8wsVuo/Prototipo-de-alta-fidelidade?node-id=26%3A101) preliminar, as solicitações de alterações são:
> 
> * [ ]  Trocar a cor principal pelo que foi definido pelo grupo
> * [ ]  Adicionar a logo
> * [X]  Certificados também deveria estar no dropdown do usuário. Na nav não pois não é uma feature de acesso frequente.
> * [X]  A dashboard deveria ser o primeiro link da navbar como "Dashboard"
> * [X]  Continuar tutorial pode ser somente Tutorial
> * [X]  Os fóruns são para cada módulo. Proponham uma forma disso ficar claro no design. O fórum em si está ótimo, nao precisa mudar, so adequar onde ele se encaixa dentro do site.
> * [X]  O tutorial ta com a navegação um pouco dificil. Seria interessante adicionar umas setas   ou mudar a seleção navegação entre módulos.
> * [ ]  Antes das atividades no lado esquerdo do tutorial, deveria ter o link pro texto daquele modulo em si. Para caso esteja em uma atividade e queira retornar ao conteúdo.
> * [X]  O modelo de chat usado é mais difícil de implementar. Pensem se irão manter, mas não é obrigatório fazer a troca.

Preciso da logo em formato svg.
Quanto a cor, não está fácil fazer uma paleta com roxo. Como nosso projeto é baseado no Django Girls, nossa cor principal também deveria ser laranja e talvez seja possível usar tons mais escuros de roxo no lugar do azul para a cor secundária.

**Comment by gabiMSilva** [comment]
> > De acordo com o [protótipo](https://www.figma.com/file/RxGKd0i4iRzTrRkj8wsVuo/Prototipo-de-alta-fidelidade?node-id=26%3A101) preliminar, as solicitações de alterações são:
> > 
> > * [ ]   Trocar a cor principal pelo que foi definido pelo grupo
> > * [ ]   Adicionar a logo
> > * [x]   Certificados também deveria estar no dropdown do usuário. Na nav não pois não é uma feature de acesso frequente.
> > * [x]   A dashboard deveria ser o primeiro link da navbar como "Dashboard"
> > * [x]   Continuar tutorial pode ser somente Tutorial
> > * [x]   Os fóruns são para cada módulo. Proponham uma forma disso ficar claro no design. O fórum em si está ótimo, nao precisa mudar, so adequar onde ele se encaixa dentro do site.
> > * [x]   O tutorial ta com a navegação um pouco dificil. Seria interessante adicionar umas setas   ou mudar a seleção navegação entre módulos.
> > * [ ]   Antes das atividades no lado esquerdo do tutorial, deveria ter o link pro texto daquele modulo em si. Para caso esteja em uma atividade e queira retornar ao conteúdo.
> > * [x]   O modelo de chat usado é mais difícil de implementar. Pensem se irão manter, mas não é obrigatório fazer a troca.
> 
> Preciso da logo em formato svg.
> Quanto a cor, não está fácil fazer uma paleta com roxo. Como nosso projeto é baseado no Django Girls, nossa cor principal também deveria ser laranja e talvez seja possível usar tons mais escuros de roxo no lugar do azul para a cor secundária.

@EduardoPicolo 
- Apesar do nosso projeto ser inspirado no DjangoGirls, os nossos produtos são diferentes e completamente desvinculados, a única relação será o texto do tutorial. Sendo assim, o time decidiu na terça feira a cor principal sendo roxo e não há problema em ser diferente da cor do site do DjangoGirls.

- A logo em SVG pode ser exportada no link do Figma que está no Slack.

- A cor secundária fica pra vcs decidirem, contanto que esteja na paleta de cores do roxo.
