### ISSUE TITLE
US01 - Implementar Autenticação de Usuário

### ISSUE THREAD

**Issue by gabiMSilva** [fga-eps-mds/2020.1-Grupo4#40]
# US01 - Implementar autenticação d Usuário

## Descrição

Permite que o usuário crie seu perfil e faça login na aplicação

## Critérios de Aceitação

- [ ] Tela de login  

- [ ] Tela de Cadastro 

- [ ] Criar usuário padrão, monitor e aprendiz 

- [ ] Registrar um usuário de cada

**Comment by JaimeJuan11** [comment]
É necessário fazer tanto testes unitários quanto exploratórios? Ou somente um dos dois? Se somente um, qual? Ou é opção minha? Não de ter comentado sobre isso...

**Comment by gabiMSilva** [comment]
> É necessário fazer tanto testes unitários quanto exploratórios? Ou somente um dos dois? Se somente um, qual? Ou é opção minha? Não de ter comentado sobre isso...

Realmente não comentamos... O teste exploratório em uma funcionalidade específica é basicamente você rodar essa funcionalidade em seu computador, testar os botões, validação, etc. Imagino que vcs já façam isso quando criam uma nova funcionalidade, então sempre façam os dois testes (exploratório e unitário).

**Comment by luucas-melo** [comment]
Posso mudar a posição da senha e do e-mail na tela de cadastro? Fica melhor pra quando vai pra um tela de celular.

**Comment by JaimeJuan11** [comment]
Os testes devem ser feitos tanto no front-end quanto para o back-end?

**Comment by JaimeJuan11** [comment]
Os testes devem ser feitos tanto no front-end quanto para o back-end? Pois ao meu ver seria somente no back, certo? Que é onde seria feito o teste da model User.js...

**Comment by EduardoPicolo** [comment]
> Posso mudar a posição da senha e do e-mail na tela de cadastro? Fica melhor pra quando vai pra um tela de celular.

Não fiz o protótipo das telas mobile, mas pra resoluções menores é melhor fazer os inputs em uma unica coluna,  que não tem muito espaço horizontal.

**Comment by gabiMSilva** [comment]
> Posso mudar a posição da senha e do e-mail na tela de cadastro? Fica melhor pra quando vai pra um tela de celular.

Pode sim, só mostre pro restante de mds pra ver se todos concordam.

**Comment by gabiMSilva** [comment]
> Os testes devem ser feitos tanto no front-end quanto para o back-end? Pois ao meu ver seria somente no back, certo? Que é onde seria feito o teste da model User.js...

Sim, tão importante quanto garantir a busca no BD é saber se isso está sendo mostrado pro usuário da forma correta.

https://devporai.com.br/testes-unitarios-em-react/#:~:text=Testes%20Unit%C3%A1rios%3A%20Buscam%20testar%20um,mais%20r%C3%A1pidos%20de%20serem%20executados.

https://uncovercode.com/index.php/2019/04/01/testes-unitarios-com-react-jest-e-enzyme/

Li sobre esse Jest e parece ser o mais usado pra testes unitários em React. Não precisa ser muito elaborado por enquanto, mas tentem testar o básico.
