### ISSUE TITLE
US03 – Tutorial 

### ISSUE THREAD

**Issue by gabiMSilva** [fga-eps-mds/2020.1-Grupo4#41]
# US03 – Tutorial 

## Descrição

Desenvolver telas do tutorial com o texto extraído do MD.

## Critérios de Aceitação (se aplicável)

- [ ] Consumir programaticamente os arquivos do tutorial
- [ ] Mostrar tutorial por módulos

**Comment by estevaoreis25** [comment]
Os arquivos .md deverão ficar em qual pasta do projeto? na src?

**Comment by peHaick** [comment]
> Os arquivos .md deverão ficar em qual pasta do projeto? na src?

Acho q vai ficar na pasta assets, numa pasta separada das imagens

**Comment by gabiMSilva** [comment]
> > Os arquivos .md deverão ficar em qual pasta do projeto? na src?
> 
> Acho q vai ficar na pasta assets, numa pasta separada das imagens

Exatamente, criem uma pasta dentro de assets. Podem colocar o nome tutorial ou qualquer outro que indique pra que elas servem.

**Comment by estevaoreis25** [comment]
Sobre os módulos, eu gostaria de saber se seria bom ser dividido em módulos menores. percebi que alguns dos módulos do tutorial são mais extensos, como por exemplo o modulo "Deploy". Pensei nessa alternativa para talvez trazer um um conforto maior para a aprendiz, deixando os módulos menores e dando uma ideia de progressão no tutorial. Porém pensei também que a pessoa poderia ter a escolha de não concluir um módulo todo no momento que inicia, e sendo assim talvez não seja necessário fazer essa partição de alguns módulos.

**Comment by gabiMSilva** [comment]
> Sobre os módulos, eu gostaria de saber se seria bom ser dividido em módulos menores. percebi que alguns dos módulos do tutorial são mais extensos, como por exemplo o modulo "Deploy". Pensei nessa alternativa para talvez trazer um um conforto maior para a aprendiz, deixando os módulos menores e dando uma ideia de progressão no tutorial. Porém pensei também que a pessoa poderia ter a escolha de não concluir um módulo todo no momento que inicia, e sendo assim talvez não seja necessário fazer essa partição de alguns módulos.

Vcs podem decidir isso. Como todos os módulos devem ter atividades, tente dividí-los de modo que não seja necessário muitas atividades em um mesmo módulo pra o usuário conseguir fixar o conteúdo.
