### ISSUE TITLE
TS19 - Escrever Estrutura Analítica do Projeto (EAP)

### ISSUE THREAD

**Issue by gabiMSilva** [fga-eps-mds/2020.1-Grupo4#42]
# TS19 - Escrever Estrutura Analítica do Projeto (EAP)

## Critérios de Aceitação (se aplicável)

- [x] Adicionar na wiki
- [x] Se orientar pelo Roadmap e Backlog

**Comment by GeovanaRamos** [comment]
Ao invés de adicionar no readme o critério seria adicionar na wiki, não? No TAP mais especificamente.

**Comment by gabiMSilva** [comment]
> Ao invés de adicionar no readme o critério seria adicionar na wiki, não? No TAP mais especificamente.

Verdade, me confundi hehe
