### ISSUE TITLE
US15 - Perfil do Usuário

### ISSUE THREAD

**Issue by gabiMSilva** [fga-eps-mds/2020.1-Grupo4#51]
# US15 - Perfil do Usuário

## Descrição

Desenvolver página de ver e editar perfil.

## Solução

Detalhar o perfil do usuário de acordo com o protótipo de alta fidelidade.
Opção de editar dados do perfil (decidir quais campos são aplicáveis)

## Critérios de Aceitação (se aplicável)

- [ ] Página de perfil do usuário.
- [ ] Página de editar perfil.

**Comment by luucas-melo** [comment]
No protótipo não tem um campo para editar a senha, devemos adicionar né?

**Comment by gabiMSilva** [comment]
@luucas-melo melhor não, melhor deixar a funcionalidade de editar senha apenas se o usuário clicar em recuperar senha no login, que será feita em outra sprint

**Comment by estevaoreis25** [comment]
Na parte da edição da imagem, a imagem a ser modificada deve ser buscada a partir de uma foto do computador ou pode ser através de um link?
@GeovanaRamos

**Comment by luucas-melo** [comment]
![localhost_3000_perfil](https://user-images.githubusercontent.com/48891167/93951854-da813080-fd1d-11ea-8cd1-cbb42f1ef12a.png)
Assim que está por enquanto

**Comment by luucas-melo** [comment]
@GeovanaRamos @gabiMSilva

**Comment by estevaoreis25** [comment]
Sobre o campo de edição de imagem, acho que seria bom criar algum tipo de pop-up ou uma nova página pra poder escolher uma nova imagem, como é comum de se ver em outros sites. O que vocês acham? @GeovanaRamos @gabiMSilva

**Comment by estevaoreis25** [comment]
Essa página do perfil do usuário seria a dashboard do usuário?

**Comment by gabiMSilva** [comment]
> Essa página do perfil do usuário seria a dashboard do usuário?

<img width="1792" alt="Captura de Tela 2020-09-23 às 06 35 25" src="https://user-images.githubusercontent.com/36926637/93995318-3a4ff980-fd67-11ea-82d8-479f87a109e7.png">

Essa é a pagina de perfil. A diferença entre ela e a página de editar é que os campos não são editáveis

**Comment by gabiMSilva** [comment]
> ![localhost_3000_perfil](https://user-images.githubusercontent.com/48891167/93951854-da813080-fd1d-11ea-8cd1-cbb42f1ef12a.png)
> Assim que está por enquanto

Como o mentor pode ser homem ou mulher, pode colocar "mentor / mentora" ou "mentor (a)" ao invés de "mentora"

**Comment by gabiMSilva** [comment]
> Sobre o campo de edição de imagem, acho que seria bom criar algum tipo de pop-up ou uma nova página pra poder escolher uma nova imagem, como é comum de se ver em outros sites. O que vocês acham? @GeovanaRamos @gabiMSilva

Concordo, podem adicionar o campo de inserir/atualizar foto, mas não foquem nisso. Façam depois do restante

**Comment by luucas-melo** [comment]
Tô pensando em fazer uma mudança na foto de perfil, ao invés de colocar a imagem lá, vou colocar um input do tipo url pra escolher a imagem e deixar a foto de perfil aparecendo na navbar. Oque acham?

**Comment by GeovanaRamos** [comment]
> Tô pensando em fazer uma mudança na foto de perfil, ao invés de colocar a imagem lá, vou colocar um input do tipo url pra escolher a imagem e deixar a foto de perfil aparecendo na navbar. Oque acham?

Ao invés da pessoa fazer  o upload ela insere um link? Tranquilo. É bom por umas orientações de site pra pessoa subir a foto algo assim.

**Comment by luucas-melo** [comment]
Ficou assim o perfil do Will Smith

![localhost_3000_perfil (1)](https://user-images.githubusercontent.com/48891167/94212416-86578700-feaa-11ea-8310-99ad9c32f3a6.png)

**Comment by gabiMSilva** [comment]
> Ficou assim o perfil do Will Smith
> 
> ![localhost_3000_perfil (1)](https://user-images.githubusercontent.com/48891167/94212416-86578700-feaa-11ea-8310-99ad9c32f3a6.png)

@luucas-melo Essa opção de mentor ou aprendiz não pode ser editada

**Comment by luucas-melo** [comment]
Nem se colocar uma condicional pra ver se a pessoa terminou os módulos?

**Comment by gabiMSilva** [comment]
> Nem se colocar uma condicional pra ver se a pessoa terminou os módulos?

Não, pq isso vai ser feito automático. A pessoa vai terminar o curso e se ela quiser vai ser "promovida" a monitor. Mas não vai ser feito aí

**Comment by luucas-melo** [comment]
> > Nem se colocar uma condicional pra ver se a pessoa terminou os módulos?
> 
> Não, pq isso vai ser feito automático. A pessoa vai terminar o curso e se ela quiser vai ser "promovida" a monitor. Mas não vai ser feito aí

Então devo tirar esse "tipo de perfil"?
