### ISSUE TITLE
US04 – Atividades

### ISSUE THREAD

**Issue by gabiMSilva** [fga-eps-mds/2020.1-Grupo4#52]
# US04 – Atividades

## Descrição

Criar e implementar telas de atividades no fórum.

## Solução

Ler tutorial e escrever perguntas de múltipla escolha em todos os módulos.
Adicionar as telas de acordo com as perguntas criadas.

## Critérios de Aceitação (se aplicável)

- [x] Cada módulo deve ter, no mínimo, 1 atividade.
- [x] Deve haver um indicativo de quando o usuário acertou ou errou a resposta.
- [x] Caso o usuário erre a resposta, o módulo deve continuar com o status de não concluído (e isso deve ser indicado no frontend)
- [x] Adicionar módulos no dropdown

**Comment by Rocsantos** [comment]
Nós acabamos decidindo que @EduardoPicolo e @peHaick ficariam responsável por desenvolver o front e back da atividade. E @JaimeJuan11 e eu (@Rocsantos) ficamos responsável por consumir o tutorial e desenvolver as questões.

Pergunta... Sendo todas as questões de múltipla escolha, a ordem das alternativas serão sorteadas de forma randômica?

**Comment by gabiMSilva** [comment]
Pode ser de forma aleatória mesmo, acho uma boa ideia. Mas isso não é critério, façam da forma mais simples e depois melhorem se der tempo

**Comment by JaimeJuan11** [comment]
Tenho uma dúvida sobre a elaboração das perguntas, devem ser seguidos os módulos desse endereço -> https://tutorial.djangogirls.org/pt/, certo? Tem que ser seguido as ordens desde 'Introdução' até 'O que vem agora?'? Mesmo para os módulos iniciais, como instalação, configuração, tem que ser feito atividades?

**Comment by JaimeJuan11** [comment]
Os próximos módulos só podem ser liberados após a leitura e execução das atividades?

**Comment by gabiMSilva** [comment]
> Tenho uma dúvida sobre a elaboração das perguntas, devem ser seguidos os módulos desse endereço -> https://tutorial.djangogirls.org/pt/, certo? Tem que ser seguido as ordens desde 'Introdução' até 'O que vem agora?'? Mesmo para os módulos iniciais, como instalação, configuração, tem que ser feito atividades?

Sim, para todos os módulos deve ter pelo menos uma atividade.
E sim tbm, tem que seguir a ordem do tutorial do Django Girls

**Comment by gabiMSilva** [comment]
> Os próximos módulos só podem ser liberados após a leitura e execução das atividades?

Não, qualquer módulo pode ser acessado a qualquer momento. Mas o certificado só será liberado após o usuário responder todas as atividades. Caso o usuário erre a resposta, aquele módulo vai ficar como não concluído.

**Comment by JaimeJuan11** [comment]
São questões de múltiplas escolhas, certo? Devem ser com 4 alternativas, até a letra 'd', ou 5 alternativas, ate a letra 'e'?

**Comment by Rocsantos** [comment]
Enquanto o @EduardoPicolo e o @peHaick estão desenvolvendo o sistema de atividade. O @JaimeJuan11 e eu iremos utilizar o nosso drive de MDS, chamado TODO - Questões da Atividade, para adicionar as questões e alternativas de cada módulo, seria bom se tanto @gabiMSilva  e @GeovanaRamos revisassem, quanto os integrantes de MDS, incluindo @estevaoreis25 e @luucas-melo .

**Comment by gabiMSilva** [comment]
> São questões de múltiplas escolhas, certo? Devem ser com 4 alternativas, até a letra 'd', ou 5 alternativas, ate a letra 'e'?

Vocês decidem. Podem escolher isso de acordo com cada questão

**Comment by gabiMSilva** [comment]
> Enquanto o @EduardoPicolo e o @peHaick estão desenvolvendo o sistema de atividade. O @JaimeJuan11 e eu iremos utilizar o nosso drive de MDS, chamado TODO - Questões da Atividade, para adicionar as questões e alternativas de cada módulo, seria bom se tanto @gabibguedes e @GeovanaRamos revisassem, quanto os integrantes de MDS, incluindo @estevaoreis25 e @luucas-melo .

Boaa! Vamos dar uma olhada sim, mas não nos esperem para começar a fazer
Marcou a Gabi errada hehe

**Comment by GeovanaRamos** [comment]
Ok! @Rocsantos, vou acompanhar lá também. Lembretes:
- Lembrem de seguir o [DER](https://fga-eps-mds.github.io/2020.1-Minacademy-Wiki/documentos/imagens/diag-bd.png) pois ele modela muito bem essa parte. Mas ajustem o que for necessário como as chaves e nomeação das variáveis.
- Como critério de aprovação queremos também a correção dos módulos no dropdown (como foi dito na reunião), pois só assim iremos testar. O Estevão já criou o arquivo que popula os módulos no banco. Basta consumir.
- Realizem as ligações com o módulo que já existe como model. Vocês vão recuperar as atividades corretas em cada página com base no módulo em que ele está vinculado no banco.

Se atentem a tudo que eu disse acima. Tudo isso já foi comentado, mas estou relembrando e registrando.

**Comment by JaimeJuan11** [comment]
O módulo 2 e 3, Instalação e Configuração do Chromebook, respectivamente, serão apresentados, tem de se montar questões a respeito? Tendo em vista que no módulo 2 tem: "Se você estiver fazendo o tutorial em casa e não em um dos eventos Django Girls, pode pular este capítulo e ir direto para o capítulo Como a internet funciona.", que seria o módulo 4, além de as instalações presentes nos respectivos módulos serem instaladas com o seguimento do tutorial como escrito também no modulo 2: "Você irá instalar tudo o que precisa no seguimento do tutorial.".

**Comment by gabiMSilva** [comment]
@JaimeJuan11 Sim, pode colocar em todos. A pessoa que já sabe não vai ter dificuldade pra responder e não prejudica o aprendizado de quem ainda não sabe

**Comment by JaimeJuan11** [comment]
Questões de internet não podem ser usadas, certo?

**Comment by GeovanaRamos** [comment]
> Questões de internet não podem ser usadas, certo?

Não. Deve ser 100% relacionado ao que está no módulo a que a pergunta se refere e deve ser original.

**Comment by GeovanaRamos** [comment]
Reforçando os critérios 2 e 3 da issue, toda essa parte do DER deve ser contemplada:
![image](https://user-images.githubusercontent.com/31005087/94157299-7793b480-fe57-11ea-9d61-89810cfaf237.png)
No caso dos histórico do usuário (que no DER foi chamado de Question_Result), como não temos o aprendiz ainda, fica a critério vocês já fazerem a especialização ou apontar apenas para o user. No último caso, será posteriormente ajustado após as stories de aprendiz/mentor.

**Comment by Rocsantos** [comment]
Recomendo que façamos a união do módulo "Instalação" e do módulo "Configuração do Chromebook". Para isso iremos atualizar a branch referente ao [US03](https://github.com/fga-eps-mds/2020.1-Minacademy-Wiki/issues/41) ?

**Comment by GeovanaRamos** [comment]
> Recomendo que façamos a união do módulo "Instalação" e do módulo "Configuração do Chromebook". Para isso iremos atualizar a branch referente ao [US03](https://github.com/fga-eps-mds/2020.1-Minacademy-Wiki/issues/41) ?

Não. Façam na branch atual mesmo.
