### ISSUE TITLE
Bugfix - Corrigir fluxo de cadastro

### ISSUE THREAD

**Issue by gabiMSilva** [fga-eps-mds/2020.1-Grupo4#55]
# Bugfix - Corrigir fluxo de cadastro

## Critérios de Aceitação (se aplicável)

- [x] Se SE IDENTIFICA COMO MULHER, escolher entre aprendiz e mentor. 

   - [x] No caso de aprendiz, mensagem de bem-vindo, explicação básica e prossegue para dashboard. 

   - [ ] No caso de mentor, explicar regras, usuário aceita, e passa a ser usuária em espera para ser monitora até atender os criterios OU ela aceita a fazer o tutorial para se tornar mentora, e acaba virando aprendiz. Lembrar que uma aprendiz que conclui vira automaticamente mentora.

- [x] Se NÃO SE IDENTIFICA COMO MULHER, mensagem explicando que é automaticamente mentor, explicar pq a iniciativa é para mulheres. Vira mentor em espera, até atender os criterios (a definir)

- [x] Essas explicações após cadastro também devem existir em uma pequena FAQ na home.

- [x] Especificar erros do cadastro.

   - [x] email já utilizado
   - [x] senha fraca
   - [x] Pelo menos 2 nomes (nome e sobrenome)
   - [x] Problema técnico deixar erro genérico
   - [x] Procurar outros erros possíveis

**Comment by Rocsantos** [comment]
A mensagem de boas vindas e explicação básica é uma nova página?
Qual são os parâmetros para uma senha fraca/forte?

**Comment by GeovanaRamos** [comment]
> A mensagem de boas vindas e explicação básica é uma nova página?

Não necessariamente. Imaginem um homem encarando nossa página de cadastro. Pra ele nao fica claro que ele nao pode marcar que quer ser aprendiz. As opções sao vcs bloquearem o checkbox e perguntarem ANTES o genero, ou quando ele clicar em submeter aparece um pop-up explicando "Olá, nossa plataforma aceita aprendizes somentes mulheres etc etc" e pede pra ele trocar. Se coloque no lugar do usuário e pense em uma forma de informar as restrições do cadastro.

Detalhe: não coletamos o gênero no cadastro. Isso é necessário para implementar as restrições.

> Qual são os parâmetros para uma senha fraca/forte?

Fica a critério de vcs.

**Comment by Rocsantos** [comment]
Adicionamos um dropdown para selecionar o gênero do usuário e a verificação de senha fraca
![Captura de Tela_20201007193404](https://user-images.githubusercontent.com/42697323/95395155-4fcf3280-08d4-11eb-8f98-f245c2de22d7.png)
O dropdown agora está responsivo e atualiza quando seleciona o gênero feminino para mostrar a opção de aprendiz
![Captura de Tela_20201007193421](https://user-images.githubusercontent.com/42697323/95395165-53fb5000-08d4-11eb-87f6-5acbc3385309.png)

PS: Quando o Dropdown está em selecione, não permite que o usuário avance no cadastro, e aparece um span de campo obrigatório

**Comment by Rocsantos** [comment]
Como iremos definir quando o usuário terminou o tutorial, sem o bugfix de atividades?

**Comment by GeovanaRamos** [comment]
> Adicionamos um dropdown para selecionar o gênero do usuário e a verificação de senha fraca

Muito bom!!

> Como iremos definir quando o usuário terminou o tutorial, sem o bugfix de atividades?

A implementação em si será contemplada na história de mentoria. Aqui iremos tratar **apenas o fluxo de cadastro e frases informativas.** Quando chegar o momento, a restrição deverá ser implementada e atrelada ao que vcs fizeram, por isso é requisito ter o "ambiente preparado". Portanto, transformei em lembrete na issue a parte que contempla a IMPLEMENTAÇÃO.

Sendo assim, o que resta pra vcs? **Quando alguem se cadastra como mentor, ele ficará "em espera"** como explicado na issue. A issue de vcs contempla essa espera. Então vcs terão de propor uma **solução criativa** para isso ficar **visível e bem compreensivel** no site, de que esse mentor não atendeu o critério(provelmente será um mini teste ou algo do tipo, iremos decidir). Já a parte que vai tirar ele "da espera" será feito na issue de mentoria.

PS: Postem aqui como ficou a FAQ. Vi que marcaram como feito. 
PS2: Atenção no português!! Atenção nas pontuações.

**Comment by peHaick** [comment]
![Screenshot from 2020-10-08 18-42-10](https://user-images.githubusercontent.com/57498006/95516866-44dcd680-0996-11eb-8f66-1164f86f06cc.png)
Ainda precisamos atualizar assim que as condições pra se tornar mentor forem definidas

**Comment by GeovanaRamos** [comment]
Repassando os comentários do PR pra cá @Rocsantos :

* A interface e as mensagens devem ser condizentes com o tipo de usuário logado. 
    1. Frases na dashboard
    2. Links da Nav
    3. Habilitação das atividades (mostrar só garabarito ou outra solução criativa)
    4. Se for monitor em espera o site deve informá-lo a todo momento e desabilitar algumas funções das proximas issues.
* Rever modelagem de usuário
    - Habilitar estado de "Monitor em espera"
    - Realizar a especialização de usuários se necessário.
* Melhorias na faq
   -  Ver se todas as duvidas sobre o site estao contempladas lá. Usar testes de usabilidade como referência.
   - Está colado no footer
   - Tentar melhorar o design. Vide exemplo abaixo

![image](https://user-images.githubusercontent.com/31005087/95653745-6098c780-0ad1-11eb-8c52-1e41637c71ed.png)

Reabram o PR quando estiver pronto para revisão. Façam rebase. Testes do back devem estar passando.

**Comment by Rocsantos** [comment]
> A interface e as mensagens devem ser condizentes com o tipo de usuário logado.
> Links da Nav

Os links da navbar não são gerais para todos?
Não me lembro de haver algo que seja exclusivo do Mentor, ou exclusivo do Aluno...
Ou nada que foi implementado ainda

> Habilitação das atividades (mostrar só garabarito ou outra solução criativa)

No momento eu tirei as atividades... Posso manter assim?

> Se for monitor em espera o site deve informá-lo a todo momento e desabilitar algumas funções das proximas issues.

Receber a informação na notificação?

Os mentores em espera terão acesso ao Tutorial? Ou só quando forem aprovados?

**Comment by GeovanaRamos** [comment]
> Os links da navbar não são gerais para todos?

Realmente, até o momento dropdown e nav são iguais.

> No momento eu tirei as atividades... Posso manter assim?

Pode. O ideal é que fique com o gabarito, mas pode.

> Receber a informação na notificação?

Não,  no momento não. Tem de ficar exposto no site, como no perfil por exemplo. O mais importante é ele ter esse status gravado no banco para ficar pronto para uso na #75, de forma que somente conferindo o status do mentor, ele fique empedido de solicitar aprendizes ou algo do tipo. Até o momento, acho que no perfil é suficiente, desde que corretamente implementado no backend.

> Os mentores em espera terão acesso ao Tutorial? Ou só quando forem aprovados?

Sim. Já que o tutorial é open-source nao faz mal ele ter acesso **considerando que vc tirou as atividades**. O certo é que elas mostrem o gabarito, então nesse caso ele não poderia ter acesso para não poder ver o gabarito.
