### ISSUE TITLE
Bugfix - Interface

### ISSUE THREAD

**Issue by gabiMSilva** [fga-eps-mds/2020.1-Grupo4#56]
# Bugfix - Interface

## Critérios de Aceitação (se aplicável)

- [x] Estilizar alertas de erro para modal
- [x] Revisar o português em todos os textos e mensagens de erro do site. 
  - [x] Padronizar mensagens
- [x] Espaço em branco abaixo do footer (aparentemente somente no Firefox).
- [x] Interface checada nos navegadores apontados no doc visão?
- [x] Footer
  - [x] Conteúdo torto
  - [x] Links inexistentes
- [x] Navbar incorreta 
  - [x] Proporção da navbar e outros elementos.
  - [x] Ícone de notificações mal posicionado
  - [x] Link da dashboard deve ser naturalmente o primeiro, links organizados por ordem de frequência de acesso.  
  - [x] Na nav somente coisas de acesso frequente, no dropdown, coisas de acesso menos frequente. 
    - [x] Certificado não precisa estar na nav. Página de uso menos frequente.
  - [x] A navbar da home deve conter as seções da página, e os links da nav, quando clicados, devem levar a seção a que eles correspondem. A página deve descer até a seção correta.
  - [x] Na home, deve haver link para entrar e cadastro. 
- [x] Mudar nome do site na aba
- [x] Padronizar fundo
- [x] Ordem das caixas de cadastro
- [x] Lembrete: Experiência inclusiva. Plataforma acolhedora. Mensagens, confete, emojis etc

**Comment by GeovanaRamos** [comment]
@luucas-melo e @EduardoPicolo mantenham lista da issue atualizada a medida que forem corrigindo o que foi pedido, marcando o que foi concluído.

**Comment by luucas-melo** [comment]
Coloquei o botão de cadastrar aí, pode ser?
![image](https://user-images.githubusercontent.com/48891167/94734744-0add5600-0340-11eb-8971-e3860bdc53f1.png)

**Comment by gabiMSilva** [comment]
> Coloquei o botão de cadastrar aí, pode ser?
> ![image](https://user-images.githubusercontent.com/48891167/94734744-0add5600-0340-11eb-8971-e3860bdc53f1.png)

Eu não gostei muito dele aí, ficou um pouco deslocado, sei lá. É muito complicado pra colocar na navbar?

**Comment by luucas-melo** [comment]
> Eu não gostei muito dele aí, ficou um pouco deslocado, sei lá. É muito complicado pra colocar na navbar?

Não é não, só achei que ficaria melhor, mas posso colocar na navbar msm

**Comment by GeovanaRamos** [comment]
Até entendo o porquê. Na nav pode ficar meio abarrotado, mas nesse local ai fica um pouco estranho mesmo. Se vc quiser, pode mudar o design do botão, caso não fique legal, ou, ao invés de botão, colocar links na tonalidade roxa.

**Comment by luucas-melo** [comment]
Pra celular ficou assim 
![image](https://user-images.githubusercontent.com/48891167/94737871-f2236f00-0344-11eb-81d5-9ead29c44ee1.png)

Pra pc assim
![image](https://user-images.githubusercontent.com/48891167/94737939-0b2c2000-0345-11eb-84be-b467e7585cb3.png)

**Comment by EduardoPicolo** [comment]
![image](https://user-images.githubusercontent.com/49292747/94856685-b5b84780-0406-11eb-8295-2e1050055b69.png)

proporções da navbar corrigidas
