### ISSUE TITLE
Bugfix - Servidor e deploy

### ISSUE THREAD

**Issue by gabiMSilva** [fga-eps-mds/2020.1-Grupo4#58]
# Bugfix - Servidor e deploy

## Critérios de Aceitação (se aplicável)

- [x] Proteger as portas do servidor
- [ ] Popular homologação
- [x] Fazer release e checar produção.
- [x] Adicionar dns

**Comment by GeovanaRamos** [comment]
- DNS criado no freenom, tanto para hom como prod (hom-minacademy.tk e minacademy.tk). Já mapeado no digitalocean para hom. Falta prod.
- Banco será populado pelo mongo compass. Aguardar últimos merge para pegar os arquivos json.

**Comment by GeovanaRamos** [comment]
Está tudo preparado. Depende das entregas agora pra propagar.
