### ISSUE TITLE
TS24 - Preparar release 1

### ISSUE THREAD

**Issue by gabiMSilva** [fga-eps-mds/2020.1-Grupo4#59]
# TS24 - Preparar release 1

Fazer os slides para posterior gravação.

## Critérios de Aceitação (se aplicável)

   - [x] Contextualização 
   - [x]  EAP 
   - [x] Divisão especial de papéis 
   - [x] canais de informação 
   - [x] Riscos 
   - [x] Custos 
   - [x] Velocity 
   - [x]  Motivação
   - [x]  MERN 
   - [x] Protótipo baixa 
   - [x] Protótipo alta 
   - [x] Homologação/Produção

**Comment by GeovanaRamos** [comment]
https://docs.google.com/presentation/d/1LD9ig-pRF2-DOtHrAGZF2KV154AgWg5n1T6zbk9pw6M/edit#slide=id.g8ca31e2d25_0_2692
