### ISSUE TITLE
US19 - Recuperação de senha

### ISSUE THREAD

**Issue by gabiMSilva** [fga-eps-mds/2020.1-Grupo4#60]
# US19 - Recuperação de senha

## Descrição

Usuário deve conseguir recuperar sua senha quando esquecer ou trocá-la quando desejar.

## Solução

Fazer a funcionalidade de recuperação de senha, que estará disponível na página de login.

[Se for uma featura nova entrar em detalhes sobre o que deve ser feito.]

## Critérios de Aceitação (se aplicável)

- [ ] Link na página de login
- [ ] Envio de e-mail para o usuários explicando os passos
- [ ] Criar tela de nova senha
- [ ] Verificar modificações no servidor

**Comment by estevaoreis25** [comment]
> Sobre como ficaria esse fluxo de recuperação de senha. Eu e o @JaimeJuan11 pensamos da seguinte forma. Teria um link na pagina de Login escrito "esqueci minha senha", clicando nela abriria um pop-up pedindo o email cadastrado para enviar um email com uma nova senha. A pessoa receberia e entraria na conta, e ela mesma decidiria se alteraria ou nao essa senha. o que vocês acham @gabiMSilva @GeovanaRamos? sugerem algo diferente ou assim parece válido? 


Eu prefiro que no email tenha um link pro usuário alterar a senha direto. O que vc acha, Geovana?

**Comment by gabiMSilva** [comment]
Eu tbm quero ver outra coisa com vcs. Penso em uma entrega até amanhã só a parte do e-mail. E a partir dessa primeira parte vcs tratam apenas a parte das telas e backend, pode ser? @estevaoreis25 @JaimeJuan11

**Comment by GeovanaRamos** [comment]
> Teria um link na pagina de Login escrito "esqueci minha senha"

 Na verdade já existe, só façam a conexão com o back.

> clicando nela abriria um pop-up pedindo o email cadastrado para enviar um email com uma nova senha. 

Depende da usabilidade. Se não ficar claro pro usuário o que ta acontecendo, usem uma página. Se for modal, caprichem na usabilidade.

> A pessoa receberia e entraria na conta, e ela mesma decidiria se alteraria ou nao essa senha. 

Na verdade não existe essa decisão, a senha DEVE ser trocada. Mandem o email de recuperação com um link que redireciona para a página de troca de senha. Pode ser o mesmo design de login/cadastro exceto que na caixa branca tem os input de nova senha e confirmação de nova senha. Após isso, redirecionar pro login.

PS: reparem que não pode ser um link qualquer, pois ele é exclusivo pra troca de conta daquele usuário. Portanto o link carrega essas informações.

**Comment by gabiMSilva** [comment]
> Eu tbm quero ver outra coisa com vcs. Penso em uma entrega até amanhã sem a parte do e-mail. E a partir dessa primeira parte vcs tratam apenas a parte do e-mail, pode ser? @estevaoreis25 @JaimeJuan11

Ficaria assim. Até amanhã:

- Envio de e-mail pronto com o template

Depois:

- Tela de colocar o email pra recuperação
- Tela de colocar a nova senha
- Backend pra trocar a senha
- Link com um token de autenticação para o usuário trocar sua senha ao clicar (no e-mail)

**Comment by estevaoreis25** [comment]
> Eu tbm quero ver outra coisa com vcs. Penso em uma entrega até amanhã só a parte do e-mail. E a partir dessa primeira parte vcs tratam apenas a parte das telas e backend, pode ser? @estevaoreis25 @JaimeJuan11

pode sim, vou tentar deixar essa parte pronta até amanha
