### ISSUE TITLE
Bugfix - Atividades

### ISSUE THREAD

**Issue by gabiMSilva** [fga-eps-mds/2020.1-Grupo4#67]
# Bugfix - Atividades

## Descrição

Resolver detalhes na feature de atividades

## Critérios de Aceitação (se aplicável)

- [x] Mostrar % de conclusão do curso na dashboard
- [x] Mostrar quantidade de atividades concluídas no curso
- [x] Mostrar quantidade de atividades restantes na dashboard
- [x] Mostrar % de conclusão do módulo no curso (embaixo do título do módulo)
- [x] Corrigir a modelagem de dados para o progresso ser mapeado por atividade
- [x] Não registrar resultado e sim alternativa escolhida. Coletar resultado comparando alternativa escolhida e se ela é a correta.
- [x] Implementar como no DER. Caso contrário, justificar antes de implementar.

**Comment by GeovanaRamos** [comment]
Pessoal, tenho algumas sugestões de interface. Acredito que o @luucas-melo deve lembrar de algumas
![image](https://user-images.githubusercontent.com/31005087/95111787-662f8f80-0716-11eb-80b0-c3418bda749a.png)

1. Seria interessante ter o dropdown dos módulos também na visão das atividades. Ele faz falta quando estamos navegando.
2. O módulo em si (o texto do tutorial) também deveria ter um link na lateral esquerda, assim como tem "Atividade 1, Atividade 2". Então o botão voltar e botão próximo deveria navegar entre o texto e as atividades, sem mudar os itens da tela.
3. A caixa que carrega o conteúdo da página muda de tamanho dependendo da atividade. Essa caixa deveria ter um tamanho fixo, mesmo em uma atividade com pouco texto.
4. Os botões não seguem o padrão do site, além de não estarem nada agradáveis visualmente. Coloquem um em cada ponta. Assim como nas páginas de texto do tutorial.

**Comment by luucas-melo** [comment]
> Pessoal, tenho algumas sugestões de interface. Acredito que o @luucas-melo deve lembrar de algumas
> ![image](https://user-images.githubusercontent.com/31005087/95111787-662f8f80-0716-11eb-80b0-c3418bda749a.png)
> 
> 1. Seria interessante ter o dropdown dos módulos também na visão das atividades. Ele faz falta quando estamos navegando.
> 2. O módulo em si (o texto do tutorial) também deveria ter um link na lateral esquerda, assim como tem "Atividade 1, Atividade 2". Então o botão voltar e botão próximo deveria navegar entre o texto e as atividades, sem mudar os itens da tela.
> 3. A caixa que carrega o conteúdo da página muda de tamanho dependendo da atividade. Essa caixa deveria ter um tamanho fixo, mesmo em uma atividade com pouco texto.
> 4. Os botões não seguem o padrão do site, além de não estarem nada agradáveis visualmente. Coloquem um em cada ponta. Assim como nas páginas de texto do tutorial.

Os botões já estão um em cada ponta, a sua develop tá atualizada?

**Comment by GeovanaRamos** [comment]
> Os botões já estão um em cada ponta, a sua develop tá atualizada?

Pode ser porque estou no firefox. Vejam se acontece o mesmo no firefox de vocês.
