### ISSUE TITLE
US06 - Pedir monitor

### ISSUE THREAD

**Issue by gabiMSilva** [fga-eps-mds/2020.1-Grupo4#74]
# US06 - Pedir monitoria 

## Descrição

O aprendiz deve conseguir solicitar um monitor que a ajude em dúvidas e problemas com o conteúdo do tutorial.

## Critérios de Aceitação (se aplicável)

APENAS APRENDIZ
- [x] Deve selecionar, no cadastro ou em tela seguinte, se deseja ou não um monitor
- [x] Caso deseje, assim que o cadastro for concluído deve ser feita uma busca por monitor disponível, e já fazer a alocação
- [x] Mentor deve ser atribuído de acordo com alguma lógica (ex: monitor que espera a mais tempo) 
- [x] Caso não deseje, deve ter a possibilidade de o usuário solicitar um monitor depois do cadastro concluído
- [x] Caso não haja monitor disponível, isso deve ser informado ao usuário, e ele deve receber um monitor assim que haja um disponível. 
- [x] Mostrar nome do monitor vinculado (caso possua)
- [x] Um aprendiz só pode ter um monitor
- [x] Critério extra: não existem restrições de interface, porém a entrega deve ter um nivel qualidade e usabilidade aceitável. Informações e navegação devem estar agradáveis, visíveis e de fácil uso. Quanto mais importante uma informação ou funcionalidade, mais visível e acessível ela deve estar.
- [x] Testes: cobertura >90% no back todos passando
- [ ] Testes: cobertura  >30% no front todos passando
- [ ] Lint passando

PS: por estarem relacionados pode ser feito na mesma branch que #75

**Comment by estevaoreis25** [comment]
Na reunião passada vocês comentaram sobre deixar disponível um pedido de mentoria dentro da pagina do tutorial, porem eu e o @peHaick estávamos pensando que seria melhor deixar essa opção na dashboard em vem vez do tutorial. Lembrando que essa opção também vai estar disponível  no momento do cadastro. Gostaria de saber oq voces @GeovanaRamos e @gabiMSilva  acham disso.

**Comment by estevaoreis25** [comment]
Mais uma pergunta. O quinto critério de aceitação diz pra se caso não tiver um monitor disponível, deve receber um assim que possível, porem eu acho que isso faz parte da issue da outra dupla. Pensei isso porque acho que quando o monitor se colocar como disponível, ele pode verificar os pedidos de monitoria e receber um, uma logica que seria criada pelo outro grupo. O que pensei que poderia fazer seria criar dois atributos de pedido de monitoria como boleano e outro atributo recebendo um mentor, e ai eles verificariam se existe o pedido e se o monitor é nulo, e ai eles criariam a logica para o aluno receber um mentor. Então gostaria de saber se essa solução já seria suficiente para o critério de aceitação, ou se poderia tirar esse critério. @GeovanaRamos @gabiMSilva

**Comment by gabiMSilva** [comment]
> Na reunião passada vocês comentaram sobre deixar disponível um pedido de mentoria dentro da pagina do tutorial, porem eu e o @peHaick estávamos pensando que seria melhor deixar essa opção na dashboard em vem vez do tutorial. Lembrando que essa opção também vai estar disponível no momento do cadastro. Gostaria de saber oq voces @GeovanaRamos e @gabiMSilva acham disso.

Por mim pode ser na dashboard mesmo

**Comment by gabiMSilva** [comment]
> Mais uma pergunta. O quinto critério de aceitação diz pra se caso não tiver um monitor disponível, deve receber um assim que possível, porem eu acho que isso faz parte da issue da outra dupla. Pensei isso porque acho que quando o monitor se colocar como disponível, ele pode verificar os pedidos de monitoria e receber um, uma logica que seria criada pelo outro grupo. O que pensei que poderia fazer seria criar dois atributos de pedido de monitoria como boleano e outro atributo recebendo um mentor, e ai eles verificariam se existe o pedido e se o monitor é nulo, e ai eles criariam a logica para o aluno receber um mentor. Então gostaria de saber se essa solução já seria suficiente para o critério de aceitação, ou se poderia tirar esse critério. @GeovanaRamos @gabiMSilva

Sim, quem vai implementar isso é a outra dupla, o que vcs precisam fazer é indicar qual o andamento pro usuário. Se está esperando um monitor ficar disponível, se ainda não foi pedido um monitor ou se já tem um monitor alocado.

Independente disso, trabalhem em sintonia com a outra dupla, pois essas tarefas são relacionadas

**Comment by estevaoreis25** [comment]
> > Mais uma pergunta. O quinto critério de aceitação diz pra se caso não tiver um monitor disponível, deve receber um assim que possível, porem eu acho que isso faz parte da issue da outra dupla. Pensei isso porque acho que quando o monitor se colocar como disponível, ele pode verificar os pedidos de monitoria e receber um, uma logica que seria criada pelo outro grupo. O que pensei que poderia fazer seria criar dois atributos de pedido de monitoria como boleano e outro atributo recebendo um mentor, e ai eles verificariam se existe o pedido e se o monitor é nulo, e ai eles criariam a logica para o aluno receber um mentor. Então gostaria de saber se essa solução já seria suficiente para o critério de aceitação, ou se poderia tirar esse critério. @GeovanaRamos @gabiMSilva
> 
> Sim, quem vai implementar isso é a outra dupla, o que vcs precisam fazer é indicar qual o andamento pro usuário. Se está esperando um monitor ficar disponível, se ainda não foi pedido um monitor ou se já tem um monitor alocado.
> 
> Independente disso, trabalhem em sintonia com a outra dupla, pois essas tarefas são relacionadas

Tudo bem entao, obrigado

**Comment by gabiMSilva** [comment]
@estevaoreis25 @peHaick Como está o andamento dessa atividade?
