### ISSUE TITLE
US13 - Solicitar aprendizes 

### ISSUE THREAD

**Issue by gabiMSilva** [fga-eps-mds/2020.1-Grupo4#75]
# US13 - Solicitar aprendizes 

## Descrição

O monitor deve conseguir solicitar novos aprendizes.

## Critérios de Aceitação (se aplicável)

- [x] Assim que o monitor é efetivado (passar nos critérios para ser um monitor) ele deve ser indicado como disponível para aceitar aprendizes e uma busca deve ser feita
- [x] O monitor deve possuir uma interface com um botão de "adicionar aprendiz" que fará uma busca por aprendizes e vinculará a ele
- [x] Caso não haja aprendizes interessados em monitoria isso deve ser informado ao usuário e seu status ficará como disponível para o próximo aprendiz ser alocado
- [x] Quando um aprendiz for alocado, o status do monitor ficara como indisponível e só mudará se ele clicar no botão de adicionar novo aprendiz.
- [x] Caso o monitor esteja disponível para mais um aprendiz e **não** tenha recebido o aprendiz ainda, ele pode retirar o pedido e voltar a ficar indisponível
- [x] Um mentor pode se disponibilizar para quantos aprendizes ele quiser.
- [ ] Critério extra: não existem restrições de interface, porém a entrega deve ter um nivel qualidade e usabilidade aceitável. Informações e navegação devem estar agradáveis, visíveis e de fácil uso. Quanto mais importante uma informação ou funcionalidade, mais visível e acessível ela deve estar.
- [ ] Testes: cobertura >90% no back todos passando
- [ ] Testes: cobertura  >30% no front todos passando
- [ ] Lint passando

PS: por estarem relacionados pode ser feito na mesma branch que #74

**Comment by EduardoPicolo** [comment]
> ## Critérios de Aceitação (se aplicável)
> * [ ]  Assim que o monitor se cadastra ele deve ser indicado como disponível para aceitar aprendizes e uma busca deve ser feita

Quando um mentor é registrado, ele fica em espera, então não é possível colocá-lo como disponível

**Comment by gabiMSilva** [comment]
> > ## Critérios de Aceitação (se aplicável)
> > 
> > * [ ]   Assim que o monitor se cadastra ele deve ser indicado como disponível para aceitar aprendizes e uma busca deve ser feita
> 
> Quando um mentor é registrado, ele fica em espera, então não é possível colocá-lo como disponível

Verdade. Corrigindo, isso deve ser feito quando um monitor é validado

**Comment by gabiMSilva** [comment]
@luucas-melo @EduardoPicolo Como está o andamento dessa atividade?

**Comment by luucas-melo** [comment]
> @luucas-melo @EduardoPicolo Como está o andamento dessa atividade?

80% completo

**Comment by gabiMSilva** [comment]
Pessoal, tá dando um erro aqui. Eu deixei um monitor disponível e cadastrei um novo aprendiz pedindo um monitor. Ele apareceu a mensagem que eu consegui um monitor, o monitor não aprece na tela do aprendiz, mas o aprendiz aparece na tela do monitor.

Além disso quando eu tento pedir um monitor novamente dá isso:

![Uploading Captura de Tela 2020-10-21 às 18.10.43.png…]()
