### ISSUE TITLE
US08 - Fornecer certificado ao aprendiz concluir curso

### ISSUE THREAD

**Issue by gabiMSilva** [fga-eps-mds/2020.1-Grupo4#77]
# US08 - Fornecer certificado ao aprendiz concluir curso

## Descrição

Após o aprendiz responder corretamente todos as atividades de todos os módulos, um certificado deve ser disponibilizado.

## Critérios de Aceitação

**Sobre o fluxo de recuperação do certificado**
- [x] Após o aprendiz responder a última questão que faltava corretamente, ele deve receber um aviso (pode ser um modal) de que o certificado está disponível. 
  - [x] Nesse modal ele terá a opção de ver o certificado ou não. 
  - [x] Nesse modal deve ter a informação de que ele pode acessar o certificado a qualquer momento pela dashboard.
- [x] Na dashboard deve ter um card que abre a lista de certificados (futuramente os certificados de monitoria também serão colocados nessa lista)
  - [x] Nessa lista deve estar o certificado de conclusão de curso
- [x] Ao clicar no certificado, a página com o certificado deverá ser aberta
  - [x] Essa página não possui a estrutura comum do site (navbar, footer, etc), apenas as informações do certificado.
- [x] A url do certificado deve ser pública para futuramente implementarmos o seu compartilhamento nas redes sociais
---
**Sobre o certificado**
- [x] Deve possuir informações pessoais
  - [x] Nome completo do aprendiz
- [x] Deve possuir informações sobre o tutorial
  - [x] Nome do curso
  - [ ] Quantidade de atividades
  - [x] Data de término do curso
  - [x] Carga horária estimada (verificar se tem algo sobre isso no Django Girls)
- [x] Deve possuir um código identificador único em todo o sistema para futuramente implementarmos a validação
  - [x] Esse código não pode ser só um número pelo motivo de facilitar a geração de um certificado falsificado. A menos que esse número seja criptografado.
---
- [x] Testes: cobertura >90% no back todos passando
- [ ] Testes: cobertura  >30% no front todos passando
- [ ] Lint passando

## Outras informações
- Exemplo de Certificado: https://cursos.alura.com.br/certificate/0c629744-091e-4c2b-91bc-c323591efc5a
- Nesse caso eles possuem uma imagem de fundo e apenas as informações pessoais e sobre o curso são texto. Caso queiram fazer assim, tudo bem, mas podem sugerir outras formas como gerar ele completamente em html.

**Comment by gabiMSilva** [comment]
Exemplo do mesmo certificado todo em HTML:

<img width="1792" alt="Captura de Tela 2020-10-17 às 13 44 39" src="https://user-images.githubusercontent.com/36926637/96348640-a977ef80-1080-11eb-82f1-9891b3da3d67.png">

**Comment by estevaoreis25** [comment]
Sobre a questão da cargar horária. eu dei uma olhada no site sobre o cronograma de um desses eventos, [link do evento](https://djangogirls.org/brasilia/) , e vi que o workshop tem a duração de 5 horas. O lucas tinha estimado 6 horas. Tudo bem manter essa estimativa?

**Comment by gabiMSilva** [comment]
> Sobre a questão da cargar horária. eu dei uma olhada no site sobre o cronograma de um desses eventos, [link do evento](https://djangogirls.org/brasilia/) , e vi que o workshop tem a duração de 5 horas. O lucas tinha estimado 6 horas. Tudo bem manter essa estimativa?

Sim. Considerando que tem as atividades também, faz sentido
