### ISSUE TITLE
US02 - Avaliação para Validar Monitor

### ISSUE THREAD

**Issue by gabiMSilva** [fga-eps-mds/2020.1-Grupo4#80]
# US02 - Avaliação para Validar Monitor

## Descrição

Qualquer usuário que se cadastrar como monitor, deverá passar por uma prova após o cadastro para ser validado.

## Critérios de Aceitação (se aplicável)

- [x] Assim que o usuário finalizar o cadastro, essa prova deverá aparecer.
- [x] O usuário poderá responder nesse momento ou depois
  - [ ] Deve ter um link no final do tutorial escrito: "Desejo fazer isso depois"
  - [x] Caso o usuário não tenha feito a prova ainda, deverá aparecer na dashboard que há uma avaliação disponível.
  - [x] Caso o usuário não tenha feito a prova ainda, deve ter uma informação na página de monitoria. "Você ainda não foi validado como monitor. Faça a sua avaliação (link para a prova) e tenha acesso a todas as funcionalidades de monitoria"
- [ ] Caso ele finalize a prova com, no mínimo, 70% de acerto ele deve ser validado.
- [ ] Caso o contrário, ele terá mais 2 chances para passar com a nota mínima.
- [ ] A avaliação deverá possuir pelo menos 10 questões técnicas **que avaliem se o usuário possui o conhecimento necessário para realizar a monitoria**
- [ ] Testes (front >30, back>90) e lint passando
- [ ] Usabilidade e qualidade na interface e textos

**Comment by estevaoreis25** [comment]
Como é uma prova, pensei que seria melhor ter todas as questões em uma única pagina e no final fazer a submissão. O que vocês acham @gabiMSilva e @GeovanaRamos ?

**Comment by gabiMSilva** [comment]
> Como é uma prova, pensei que seria melhor ter todas as questões em uma única pagina e no final fazer a submissão. O que vocês acham @gabiMSilva e @GeovanaRamos ?

Eu pensei assim mesmo

**Comment by estevaoreis25** [comment]
Sobre o primeiro critério de aceitação, nós optamos por mostrar antes a página de bem vindos e nessa página ter dois links para a pessoa decidir se deseja fazer a avaliação naquele momento ou se deseja fazer depois. Estando assim, esse critério é aceito? @gabiMSilva @GeovanaRamos

**Comment by estevaoreis25** [comment]
Sobre esse critério " Deve ter um link no final do tutorial escrito: "Desejo fazer isso depois", ele é referente ao aluno que deseja ser monitor? Porque acredito que nem todo aluno desejaria se tornar um monitor. Se for esse o caso, acho que poderia mudar ao menos a frase, pra algo do tipo "Se deseja se tornar um monitor, faça a avaliação para tornar-se um monitor e assim ajudar outras alunas ..." algo do tipo.

**Comment by gabiMSilva** [comment]
> Sobre o primeiro critério de aceitação, nós optamos por mostrar antes a página de bem vindos e nessa página ter dois links para a pessoa decidir se deseja fazer a avaliação naquele momento ou se deseja fazer depois. Estando assim, esse critério é aceito? @gabiMSilva @GeovanaRamos 

Sim, assim fica legal também

**Comment by gabiMSilva** [comment]
> Sobre esse critério " Deve ter um link no final do tutorial escrito: "Desejo fazer isso depois", ele é referente ao aluno que deseja ser monitor? Porque acredito que nem todo aluno desejaria se tornar um monitor. Se for esse o caso, acho que poderia mudar ao menos a frase, pra algo do tipo "Se deseja se tornar um monitor, faça a avaliação para tornar-se um monitor e assim ajudar outras alunas ..." algo do tipo. 

Essa prova é apenas para o monitor não validado. O aluno pode se tornar monitor assim que ele finaliza o tutorial com todas as questões respondidas corretamente - ou seja, assim que recebe o certificado.

Esse link estaria relacionado ao monitor que acabou de se cadastrar, foi redirecionado para a tela da prova mas não deseja respondê-la naquele momento.
