### ISSUE TITLE
US10 - Promoção de aprendiz à mentor

### ISSUE THREAD

**Issue by gabiMSilva** [fga-eps-mds/2020.1-Grupo4#84]
# US10 - Promoção de aprendiz à mentor

## Descrição

Quando um aprendiz finalizar o curso e receber seu certificado ele será convertido para mentor.

## Critérios de Aceitação (se aplicável)

- [x]  Na primeira vez que ele entrar na dashboard após a finalização do curso, ele deve ser avisado que se tornou um mentor
- [x] Ele deve ser iniciado como um mentor validado, porém indisponível.
- [x] O Certificado de finalização do curso ainda deve aparecer pra ele.

**Comment by Rocsantos** [comment]
Conforme foi implementado o usuário, e eu pesquisei a documentação do mongoose, para promover o Learner para Mentor, deve criar um novo usuário Mentor e destruir o Learner, passando todo conteúdo para o novo usuário... Porém, como a senha é criptografada deve ser solicitada antes de promover a aprendiz.

Eu posso fazer isso?

**Comment by GeovanaRamos** [comment]
Conforme esclarecemos em reunião, o histórico de aprendiz **não deve ser destruído**, para histórico e caso haja alguma auditoria. O usuário promovido a mentor deve estar registrado mo banco como mentor e aprendiz (um aprendiz inativo no caso). Se a implementação seguiu o DER não vai ter problemas para implementar e se não seguiu você deve refatorar para seguir o DER e assim tem um usuário vinculado a duas especializações.

**Comment by Rocsantos** [comment]
O histórico seria as questões respondidas, módulos concluídos e o mentor?
E quanto ao mentor... O aluno ainda ficará vinculado ao mentor mesmo depois do fim do tutorial?

**Comment by GeovanaRamos** [comment]
Não se preocupe com detalhes de mentoria, serão tratados em outras issues. Não se preocupe com o histórico. A única coisa que vc tem que garantir é que o aprendiz vai continuar existindo.
