### ISSUE TITLE
BUGFIX - Mensagens de Autenticação

### ISSUE THREAD

**Issue by gabiMSilva** [fga-eps-mds/2020.1-Grupo4#86]
# BUGFIX - Mensagens de Autenticação

## Defeitos e Correções

- Recuperar Senha
  - [x] Sem estilos;
  - [x] Mudar a mensagem de erro ao enviar email quando o e-mail não existe;
- Trocar Senha
  - [x] Sem estilos;
  - [x] Adicionar identidade visual no email;
  - [x] Não há validação das duas senhas para checar se batem;
  - [x] A página não redireciona para Login;
  - [x] Quando a api não está funcionando, o erro no cadastro é de dados incorretos e deve ser algo como "Erros internos no servidor".

**Comment by GeovanaRamos** [comment]
@peHaick @gabiMSilva  ficou faltando uma tarefa na issue. 

**Login**
- Quando a api não está funcionando, o erro no login é de dados incorretos e deve ser algo como "Erros internos no servidor". 

Adicione no PR por favor essa correção também.
