### ISSUE TITLE
BUGFIX - Página de Perfil

### ISSUE THREAD

**Issue by gabiMSilva** [fga-eps-mds/2020.1-Grupo4#87]
# BUGFIX - Página de Perfil

## Defeitos

- [x] Campos não utilizados (imagem e fale sobre você);
- [x] Não mostra o tipo de cadastro;
- [x] Botão de atualizar não está funcionando;

**Comment by estevaoreis25** [comment]
O tipo de cadastro deve ser mostrado em algum local específico? tipo abaixo do h1 "Perfil"?

**Comment by estevaoreis25** [comment]
Sobre botão de atualizar não estar funcionando, no meu pc ele está. Fiz meus testes e consigo alterar nome e e-mail e fazer o login novamente com ele alterado. Também verifiquei no insomnia e lá mostra também a alteração. Não sei se faz parte do bugfix mas a única coisa que pensei que poderia ser consertado seria redirecionar a página após a atualização. @gabiMSilva  @GeovanaRamos

**Comment by GeovanaRamos** [comment]
> O tipo de cadastro deve ser mostrado em algum local específico? tipo abaixo do h1 "Perfil"?

Não. Fica a seu critério. Mas vamos avaliar se a interface está agradável então escolha sabiamente.

> Sobre botão de atualizar não estar funcionando, no meu pc ele está. 

Por favor, confirme se:
- você consegue editar todos os campos que **vão permanacer** (nome, sobrenome, e-mail)
- você está com o reposítório local atualizado

Extra: Olhe os dados do usuário e veja se tem a necessidade de adicionar mais dados no perfil, além do tipo de cadastro. Lembrando que esse tipo não pode ser alterado, é somente informativo.

**Comment by estevaoreis25** [comment]
Após atualizar é preciso redirecionar a página?

**Comment by GeovanaRamos** [comment]
> Após atualizar é preciso redirecionar a página?

Não, mas é preciso informar que os dados foram atualizados com sucesso (ou não). Utilize a forma padrão do site com aquela nota que aparece à direita. Lembre de diferenciar os erros (deu certo, não deu, erros no servidor etc).

**Comment by estevaoreis25** [comment]
> Por favor, confirme se:
> 
>     * você consegue editar todos os campos que **vão permanacer** (nome, sobrenome, e-mail)
Eu verifiquei e realmente o campo 'sobrenome' nao estava atualizando, mas consegui arrumar
> 
>     * você está com o repositório local atualizado
Antes de criar a nova branch eu fiz o git checkout develop, dei o pull e só depois criei a branch,então estava atualizado.
> 
> 
> Extra: Olhe os dados do usuário e veja se tem a necessidade de adicionar mais dados no perfil, além do tipo de cadastro. Lembrando que esse tipo não pode ser alterado, é somente informativo.
>
O único dado que pensei que seria valido adicionar na página de perfil seria o gẽnero, mas como aprendiz sempre é feminino, não sei se seria válido. O que vocês acham @GeovanaRamos e @gabiMSilva ?

**Comment by estevaoreis25** [comment]
> Não, mas é preciso informar que os dados foram atualizados com sucesso (ou não). Utilize a forma padrão do site com aquela nota que aparece à direita. Lembre de diferenciar os erros (deu certo, não deu, erros no servidor etc).

Sobre isso, eu não sei o motivo mas nos meus navegadores, ou não aparece, ou aparece bem rápido. Fiz um teste aqui e parece que está aparecendo o toast com a mensagem de confirmação de atualização de perfil.

**Comment by GeovanaRamos** [comment]
> O único dado que pensei que seria valido adicionar na página de perfil seria o gẽnero, mas como aprendiz sempre é feminino, não sei se seria válido. O que vocês acham @GeovanaRamos e @gabiMSilva ?

Pode ser. Como campo não editável.
