### ISSUE TITLE
US16 - Notificações por e-mail

### ISSUE THREAD

**Issue by gabiMSilva** [fga-eps-mds/2020.1-Grupo4#91]
# US16 - Notificações por e-mail

## Descrição

Enviar notificações de ações importantes por e-mail.

## Critérios de Aceitação (se aplicável)

- [x] Os e-mails devem explicar minuciosamente cada atividade relatada e o que isso muda para o usuário
- [x] Padronizar o envio de e-mails
- O usuário deve ser notificado quando ocorrer os seguintes eventos:
   - [x] Aprendiz se transformar em mentor [aprendiz]
   - [x] Aprendiz receber um novo mentor [aprendiz] 
   - [x] Mentor receber um novo aprendiz [mentor]
   - [x] Aprendiz finalizar curso [mentor(se houver) e aprendiz]
   - [x] cancelamento de monitoria [monitor e aprendiz] 
   - [x] Monitor passar na avaliação [monitor]
   - [x] Monitor reprovar na avaliação [monitor]

**Comment by estevaoreis25** [comment]
o item  "cancelamento de monitoria [monitor e aprendiz]" é pra quando eles já estão vinculados ou quando ainda não existe o vínculo? @gabiMSilva @GeovanaRamos

**Comment by gabiMSilva** [comment]
> o item  "cancelamento de monitoria [monitor e aprendiz]" é pra quando eles já estão vinculados ou quando ainda não existe o vínculo? @gabiMSilva @GeovanaRamos 

Quando já estão vinculadps. É para o aluno ser avisado quando o seu mentor cancelar o vínculo e vice-versa.

**Comment by peHaick** [comment]
>   * [ ]  Monitor reprovar na avaliação [aprendiz]

É pra enviar e email para o mentor, certo? Até porque não tem como ele possuir uma aprendiz se ainda não fez a prova.

**Comment by gabiMSilva** [comment]
> >   * [ ]  Monitor reprovar na avaliação [aprendiz]
> 
> É pra enviar e email para o mentor, certo? Até porque não tem como ele possuir uma aprendiz se ainda não fez a prova.

Isso, é pro usuário que fez a prova

**Comment by GeovanaRamos** [comment]
Registrando alguns problemas e coisas que vocês tem que se preocupar em resolver nessa issue:
- [x] O envio do email no caso de troca de email deve ser enviado para o NOVO email e não o antigo.
- [x] Todos os testes que passarem por funções que enviam email vão falhar no CI. É preciso mockar o nodemailer no teste ou remover testes deste tipo (desde que dentro de 90% de cobertura).
- [x] Os links enviados nos emails devem ser modificados conforme o ambiente do site (desenvolvimento, homologação, produção).
- [ ] Os estilos e imagens não funcionam quando o email é realmente enviado para um email real.
