### ISSUE TITLE
BUGFIX - Interface

### ISSUE THREAD

**Issue by gabiMSilva** [fga-eps-mds/2020.1-Grupo4#97]
# BUGFIX - Interface

## Descrição

Correção de problemas e defeitos relacionados à usabilidade, ortografia e design da aplicação.

### Cadastro
- [x] Femino mostrado mas não marcado
### Geral
- [x] Espaço entre o footer e conteúdo;
- [x] Espaço à direita sobrando no Firefox;
- [x] Mudar pronomes de acordo com o gênero de quem acessa no momento;
- [x] “Seja bem-vind@, mentor!” no toast;
- [x] Padronizar lógica de botões à direita e à esquerda;
- [x] Link de avaliação aparece pro aprendiz;
- [x] Links estão azuis
### Bem-vind@!
- [x] Revisão geral;
- [x] Bem-vind@!;
### Home
- [x] Rolagem para as seções não é suave. [Exemplo](https://colorlib.com/preview/#ronaldo);
- [x] FAQ: faltam textos e o design precisa melhorar. [Exemplo](https://colorlib.com/preview/#skater);
- [x] FAQ: espaço entre footer e a faq
- [x] Perguntas Frequentes
- [x] Colocar faq na nav ou criar uma nova página.
### Dashboard
- [x] Padronizar maiúsculas e minúsculas;
- [x] Português: concluido -> concluído;
- [x] Português: Se tem verbo e não é título, então tem ponto final(.);
- [x] Cards no mesmo tamanho, sem borda e sombra de seleção.
- [x] Passar todos os termos com "monitoria" para "mentoria"

### Português
- [x] Geral!!

**Comment by estevaoreis25** [comment]
Esse quesito "“Seja bem-vind@, mentor!” no toast" é pra colocar de fato essa mensagem ou para mudar dependendo do gênero?

**Comment by GeovanaRamos** [comment]
> Esse quesito "“Seja bem-vind@, mentor!” no toast" é pra colocar de fato essa mensagem ou para mudar dependendo do gênero?

É pra mudar de acordo com o gênero. Somente no caso do aprendiz que você vai colocar tudo no feminino, pois temos a restrição de aprendizes. @GeovanaRamos  @gabiMSilva

**Comment by estevaoreis25** [comment]
"FAQ: faltam textos e o design precisa melhorar. Exemplo;" poderia me dar algum exemplo de uma FAQ mais completa e com um design melhor? Esse quesito ficou um pouco vago pra mim. @gabiMSilva  @GeovanaRamos

**Comment by GeovanaRamos** [comment]
> "FAQ: faltam textos e o design precisa melhorar. Exemplo;" poderia me dar algum exemplo de uma FAQ mais completa e com um design melhor? Esse quesito ficou um pouco vago pra mim. @gabiMSilva @GeovanaRamos

Acabou que na hora de colar a issue perderam-se os hyperlinks. Atualizei a issue com eles. Tem um exemplo no link com um design mais agradável. Mas dá pra pesquisar outros exemplos também. Se achar outros poste aqui.

**Comment by estevaoreis25** [comment]
" Rolagem para as seções não é suave. Exemplo;" sobre esse quesito, vai ser preciso fixar a navbar durante a rolagem? @GeovanaRamos  @gabiMSilva

**Comment by gabiMSilva** [comment]
> " Rolagem para as seções não é suave. Exemplo;" sobre esse quesito, vai ser preciso fixar a navbar durante a rolagem? @GeovanaRamos  @gabiMSilva 

Não, se preferirem podem fazer. Mas não é critério.

**Comment by estevaoreis25** [comment]
@GeovanaRamos , você lembra onde viu os links em azul? Olhei a maioria das páginas, inclusive dentro de cada md do Tutorial e nao encontrei

**Comment by GeovanaRamos** [comment]
> @GeovanaRamos , você lembra onde viu os links em azul? Olhei a maioria das páginas, inclusive dentro de cada md do Tutorial e nao encontrei

Perdão por faltar esse detalhe. Era no dropdown. Talvez tenha corrigido semana passada.

**Comment by estevaoreis25** [comment]
> > @GeovanaRamos , você lembra onde viu os links em azul? Olhei a maioria das páginas, inclusive dentro de cada md do Tutorial e nao encontrei
> 
> Perdão por faltar esse detalhe. Era no dropdown. Talvez tenha corrigido semana passada.

No do Tutorial?

**Comment by GeovanaRamos** [comment]
> > > @GeovanaRamos , você lembra onde viu os links em azul? Olhei a maioria das páginas, inclusive dentro de cada md do Tutorial e nao encontrei
> > 
> > 
> > Perdão por faltar esse detalhe. Era no dropdown. Talvez tenha corrigido semana passada.
> 
> No do Tutorial?

Não, no de perfil. No campo superior direito

**Comment by estevaoreis25** [comment]
"FAQ: faltam textos e o design precisa melhorar". Sobre essa parte mesmo vendo o exemplo, eu não sei como poderia melhorar o design, já que todos os outros textos na Home estão com o mesmo padrão. Vocês poderiam sugerir algo? @gabiMSilva  @GeovanaRamos

**Comment by estevaoreis25** [comment]
"Padronizar lógica de botões à direita e à esquerda". A maioria dos botões estão na parte de avaliação e tutorial. Como foi conversado sobre ter apenas um botão ou ter uma lógica diferente, acho que vamos acaba modificando as mesmas áreas do projeto. Será que eu deveria mesmo alterar o posicionamento dos botões em tutorial e avaliação? @GeovanaRamos  @gabiMSilva

**Comment by GeovanaRamos** [comment]
> "FAQ: faltam textos e o design precisa melhorar". Sobre essa parte mesmo vendo o exemplo, eu não sei como poderia melhorar o design, já que todos os outros textos na Home estão com o mesmo padrão. Vocês poderiam sugerir algo? @gabiMSilva @GeovanaRamos

Seria o design do exemplo mesmo.



> "Padronizar lógica de botões à direita e à esquerda". A maioria dos botões estão na parte de avaliação e tutorial. Como foi conversado sobre ter apenas um botão ou ter uma lógica diferente, acho que vamos acaba modificando as mesmas áreas do projeto. Será que eu deveria mesmo alterar o posicionamento dos botões em tutorial e avaliação? @GeovanaRamos @gabiMSilva

Não são só esses botões na plataforma, tem o de confirmação de certificado por exemplo, quando o aprendiz finaliza o curso. Deixe os de tutorial e avaliação para a issue de curso. Mas o posicionamento de ambas as issues tem que estar igual.

**Comment by Rocsantos** [comment]
Como a Geovana já tinha dado um exemplo de FAQ para mudar o design, [aqui](https://github.com/fga-eps-mds/2020.1-Minacademy-Wiki/issues/55)

Gostaria de saber se a FAQ dessa forma está mais agradável ou se eu teria que mexer na disposição das perguntas
![image](https://user-images.githubusercontent.com/42697323/99582073-59ae8000-29c0-11eb-8625-35c47988916a.png)

**Comment by estevaoreis25** [comment]
> Não são só esses botões na plataforma, tem o de confirmação de certificado por exemplo, quando o aprendiz finaliza o curso. Deixe os de tutorial e avaliação para a issue de curso. Mas o posicionamento de ambas as issues tem que estar igual.

Sobre isso eu conversei com os meninos que estão com a issue do curso. O Lucas pediu para eu nao modificar essa parte dos botoes de confirmação de certificado porque eles já fizeram essa alteração. Então deixando de lado toda a parte que envolve o curso da plataforma e a avaliação eu procurei botoes nas seguintes páginas: Dashboard, Perfil, Mentoria, Certificado, Home, Login, Cadastro, Bem-vindo, Redefinição de Senha e Recuperação de senha. Em algumas das páginas, por terem apresentações diferentes eu ainda conferi com os seguintes tipos de usuários: Aprendiz, Mentor Validado e Mentor não validado. Não encontrei botoes que se encaixem nesse quesito "Padronizar lógica de botões à direita e à esquerda;"

**Comment by GeovanaRamos** [comment]
Desculpa a demora pessoal.

> Gostaria de saber se a FAQ dessa forma está mais agradável ou se eu teria que mexer na disposição das perguntas
> ...

Rodrigo, já está bem melhor. Mas teria que ver no todo se está combinando. Olhando separadamente está ótimo.

> Não encontrei botoes que se encaixem nesse quesito "Padronizar lógica de botões à direita e à esquerda;"

Ok! Se eles já corrigiram, ótimo.
