### ISSUE TITLE
BUGFIX - Curso

### ISSUE THREAD

**Issue by gabiMSilva** [fga-eps-mds/2020.1-Grupo4#98]
# BUGFIX - Curso

## Descrição

Defeitos e erros nas áreas do curso (tutorial, atividades avaliação)

### Atividades

- [x] O texto do tutorial deve ser uma opção na side acima das atividades;
- [x] Mesma interface e botões de navegação para atividades e texto. Adicionar droopdown na visão de atividades;
- [x] Aprendiz com curso concluído não consegue navegar entre as questões. O pop-up fica aparecendo toda hora. 
   - Opções:
      - [ ] Remover acesso às questões;
      - [x] Permitir a navegação;
- [x] Aprendiz já é criado com o curso concluído. Isso não pode acontecer;
- [x] Remover “Forum”;
- [x] Português: Modulo->Módulo;
- [x] Última atividade possui botão proximo e primeira possui botão anterior;

- [x] Módulo 5 atividade 8
- [x] Módulo 12 atividade 19
- [x] Módulo 15 atividade 25
- [x] Quase sempre a C é a correta;
- [x] Deixar apenas o botão responder nas atividades. O botão próximo aparece quando o usuário acerta a questão, no mesmo local, de preferência. Se errar, aparece o de refazer.

### Mentor

- [x] Nem tutorial nem o dropdown estão centralizados;
- [x] Mentor está respondendo as atividades. Isso não pode acontecer.

### Avaliação

- [x] Botoes ao invés links ao iniciar a avaliação e o de voltar para a dashboard.
- [x] Botão próximo desalinhado. 
- [x] Botões trocados. Remover próximo e deixar apenas o responder, e ele automaticamente leva para a próxima questão.
- [x] Caixa vazia em branco após conclusão
- [x] Avaliação aprovando mesmo sem ter nota e aparece uma mensagem errada no canto superior direito
- [x] Mostrar percentual de acerto
- [x] Mentor e nao monitor
- [x] Botao de refazer nao tá claro ou aparente, além de não estar funcionando no momento

### Observações

A interface de atividades e tutorial devem ser 100% equivalentes, tanto o posicionamento de botões e a forma das questões.

**Comment by EduardoPicolo** [comment]
> ### Atividades
>  [ ]  Dropdown está levando para os modulos errados e está completamente quebrado.

Não estamos conseguindo reproduzir esse bug, dropdown aparenta estar funcionando corretamente.

**Comment by gabiMSilva** [comment]
> > ### Atividades
> >  [ ]  Dropdown está levando para os modulos errados e está completamente quebrado.
> 
> Não estamos conseguindo reproduzir esse bug, dropdown aparenta estar funcionando corretamente.
> 
> 
> 

O fluxo que fiz pra isso acontecer foi:

Ir nas primeiras atividades -> responder corretamente -> voltar para o tutorial -> escolher o próximo módulo pelo dropdown. 

Ele começa a mostrar os módulos errados no dropdown.

Reparem a ordem que os módulos mudam. Façam com o objetivo de ir sequencialmente em todos os módulos APENAS pelo dropdown.

**Comment by EduardoPicolo** [comment]
> 
>     * [ ]  Última atividade possui botão proximo e primeira possui botão anterior;
> 
>     * [ ]  Deixar apenas o botão responder nas atividades. O botão próximo aparece quando o usuário acerta a questão, no mesmo local, de preferência. Se errar, aparece o de refazer.

Esses critérios estão conflitando. 
Achamos que seria melhor os botões de navegação (próximo e anterior) sempre aparecerem, de acordo com as atividades á frente/a trás.
Não é necessário um botão de refazer, o usuário pode selecionar outra alternativa e responder. A não que "refazer" seja limpar o resultado do banco de dados.

Também estamos em duvida em qual lado colocar o botão de responder. 
#### Exemplos:

![image](https://user-images.githubusercontent.com/49292747/99362322-1b1aa780-2892-11eb-9c30-2b0a328f94d4.png)
![anterior](https://user-images.githubusercontent.com/49292747/99362346-22da4c00-2892-11eb-829e-7fc43a4ddf5d.png)

#### Exemplo de como ficaria caso a atividade estivesse no 'meio' de outras:
![image](https://user-images.githubusercontent.com/49292747/99363412-7731fb80-2893-11eb-9c15-ee77297b3137.png)
![image](https://user-images.githubusercontent.com/49292747/99363539-a34d7c80-2893-11eb-8ff4-7cefce63edf5.png)

**Comment by GeovanaRamos** [comment]
> Achamos que seria melhor os botões de navegação (próximo e anterior) sempre aparecerem, de acordo com as atividades á frente/a trás.

Não, é pra remover mesmo. Se ainda acharem necessário ter, queremos conforme modelo abaixo:

![image](https://user-images.githubusercontent.com/31005087/99390721-e588b500-28b7-11eb-97c5-4631ecc76d98.png)

Ou remover e deixar somente o Responder como solicitado, ou aplicar a mudança da imagem acima que também deverá ser aplicada nos textos, ou seja, remover os botões para navegar pela seta. A seta não precisaria ser exatamente igual a essa (cor e desenho), desde que o design "converse" com a plataforma e siga os padrões estabelecidos.

> Não é necessário um botão de refazer, o usuário pode selecionar outra alternativa e responder. A não que "refazer" seja limpar o resultado do banco de dados.

Realmente. Ok

> Também estamos em duvida em qual lado colocar o botão de responder.

Conforme já disse, quem dita é o padrão da plataforma. Por exemplo, na hora de emitir o certificado o botão visualizar e cancelar ficam em qual lado, respectivamente? Isso também é criterio na #97. Vocês devem entrar em consenso e todos os botões da plataforma seguirem a mesma lógica, confirmar/enviar em um lado e cancelar/voltar em outro.

**Comment by luucas-melo** [comment]
A navegação ficou assim: 
1- Se tiver na primeira questão o botão "anterior" fica desativado 
2- Se tiver na última questão o botão "próximo" fica desativado
3- Assim mantemos a consistência da aplicação e os botões não desparecem.
Questão não respondida: 
![image](https://user-images.githubusercontent.com/48891167/99413509-9dc45680-28d4-11eb-9fcf-d5e098775829.png)

Questão respondida:
![image](https://user-images.githubusercontent.com/48891167/99413738-de23d480-28d4-11eb-88a5-d078a8baac43.png)

**Comment by EduardoPicolo** [comment]
> > > ### Atividades
> > > [ ]  Dropdown está levando para os modulos errados e está completamente quebrado.
> > 
> > 
> > Não estamos conseguindo reproduzir esse bug, dropdown aparenta estar funcionando corretamente.
> 
> O fluxo que fiz pra isso acontecer foi:
> 
> Ir nas primeiras atividades -> responder corretamente -> voltar para o tutorial -> escolher o próximo módulo pelo dropdown.
> 
> Ele começa a mostrar os módulos errados no dropdown.
> 
> Reparem a ordem que os módulos mudam. Façam com o objetivo de ir sequencialmente em todos os módulos APENAS pelo dropdown.

Ainda não consegui reproduzir o bug. Testei de diversas maneiras, diferentes navegadores e computadores, local e homologação.

Preciso de mais informações sobre o bug: Navegador usado, versão, ambiente (dev, homolog), tipo de conta (aprendiz, mentor), se a conta foi criada antes ou depois da modificação 'isRegistered'. 

Se o bug correu só em desenvolvimento, pode ser que o docker não tenha instalado alguma dependência, visto que isso já ocorreu antes com outros membros.

**Comment by GeovanaRamos** [comment]
> A navegação ficou assim:
> ...

Por gentileza, sigam as orientações conforme já passamos e se não fizerem justifiquem o porquê.

**Comment by gabiMSilva** [comment]
> > > > ### Atividades
> > > > [ ]  Dropdown está levando para os modulos errados e está completamente quebrado.
> > > 
> > > 
> > > Não estamos conseguindo reproduzir esse bug, dropdown aparenta estar funcionando corretamente.
> > 
> > O fluxo que fiz pra isso acontecer foi:
> > 
> > Ir nas primeiras atividades -> responder corretamente -> voltar para o tutorial -> escolher o próximo módulo pelo dropdown.
> > 
> > Ele começa a mostrar os módulos errados no dropdown.
> > 
> > Reparem a ordem que os módulos mudam. Façam com o objetivo de ir sequencialmente em todos os módulos APENAS pelo dropdown.
> 
> Ainda não consegui reproduzir o bug. Testei de diversas maneiras, diferentes navegadores e computadores, local e homologação.
> 
> Preciso de mais informações sobre o bug: Navegador usado, versão, ambiente (dev, homolog), tipo de conta (aprendiz, mentor), se a conta foi criada antes ou depois da modificação 'isRegistered'. 
> 
> Se o bug correu só em desenvolvimento, pode ser que o docker não tenha instalado alguma dependência, visto que isso já ocorreu antes com outros membros.

Testei com um novo aprendiz, no Google Chrome na versão mais recente em ambiente de desenvolvimento. Não é problema de dependência pq ele gera um erro quando não encontra um pacote e isso não aconteceu. A conta foi criada depois da alteração 'isRegistered'

**Comment by EduardoPicolo** [comment]
Como ficou: botão de responder padronizado á direita, próximo só aparece ao acertar, ultima atividade com navegação pro tutorial. Preferimos não colocar um botão de voltar para não encher a página de botões.

![nevegação_ativ](https://user-images.githubusercontent.com/49292747/99532636-62349580-2983-11eb-9f2f-dc23db66f46a.gif)

**Comment by luucas-melo** [comment]
> Testei com um novo aprendiz, no Google Chrome na versão mais recente em ambiente de desenvolvimento. Não é problema de dependência pq ele gera um erro quando não encontra um pacote e isso não aconteceu. A conta foi criada depois da alteração 'isRegistered'

Não consegui reproduzir esse bug do dropdown, tentei várias vezes e de diferentes formas

**Comment by gabiMSilva** [comment]
> > Testei com um novo aprendiz, no Google Chrome na versão mais recente em ambiente de desenvolvimento. Não é problema de dependência pq ele gera um erro quando não encontra um pacote e isso não aconteceu. A conta foi criada depois da alteração 'isRegistered'
> 
> Não consegui reproduzir esse bug do dropdown, tentei várias vezes e de diferentes formas
> 

Tá bom. Continuem corrigindo os outros bugs, a @GeovanaRamos vai tentar reproduzir esse defeito e se ela conseguir voltamos nele.

**Comment by gabiMSilva** [comment]
@luucas-melo @EduardoPicolo tentamos reproduzir o problema do dropdown em homologação e o problema não persiste, então podem ignorar esse defeito

**Comment by EduardoPicolo** [comment]
>     * [ ]  Módulo 5 atividade 8
> 
>     * [ ]  Módulo 12 atividade 19
> 
>     * [ ]  Módulo 15 atividade 25

???????????????????????????

**Comment by gabiMSilva** [comment]
> > ```
> > * [ ]  Módulo 5 atividade 8
> > 
> > * [ ]  Módulo 12 atividade 19
> > 
> > * [ ]  Módulo 15 atividade 25
> > ```
> 
> ???????????????????????????

São as atividades que estão com respostas erradas, ela falou no planejamento.

Quando não souber algo sobre a issue, coloque um comentário que possa ser respondido. Essa experiência simula o ambiente de Open Source e isso não é um tipo de pergunta que se faça em um repositório aberto em um ambiente profissional.

@GeovanaRamos se quiser explicar melhor sobre as questões.

**Comment by GeovanaRamos** [comment]
> @GeovanaRamos se quiser explicar melhor sobre as questões.

**Como dito na reunião de planejamento**, existiam algumas questões duvidosas ou mal formatadas e precisavam de uma revisão de forma geral:
1 - uma sobre a linha de comando que parecia errada (mas já constatei que o tutorial realmente fala isso)
2 - uma com código de programação porém não formatada (acabei anotando o número errado então não cobrei no PR) 
3 - uma que apontava um erro que nem estava na página(a mesma que apontei no PR).

Reforço a mensagem da Gabriela e acrescento que, se ainda há dúvidas sobre um critério de aceitação, o PR nem deveria ser aberto e a questão deve ser sanada previamente aqui, pois não é possível atender um critério que não se compreende. Como sempre, estamos a disposição para esclarecer os critérios.

**Comment by luucas-melo** [comment]
> > @GeovanaRamos se quiser explicar melhor sobre as questões.
> 
> **Como dito na reunião de planejamento**, existiam algumas questões duvidosas ou mal formatadas e precisavam de uma revisão de forma geral:
> 1 - uma sobre a linha de comando que parecia errada (mas já constatei que o tutorial realmente fala isso)
> 2 - uma com código de programação porém não formatada (acabei anotando o número errado então não cobrei no PR)
> 3 - uma que apontava um erro que nem estava na página(a mesma que apontei no PR).
> 
> Reforço a mensagem da Gabriela e acrescento que, se ainda há dúvidas sobre um critério de aceitação, o PR nem deveria ser aberto e a questão deve ser sanada previamente aqui, pois não é possível atender um critério que não se compreende. Como sempre, estamos a disposição para esclarecer os critérios.

Já estou corrigindo os problemas apontados, mas como dito no PR, o mesmo foi aberto para que possam ver se o bug que tinha sido apontado nos critérios de aceitação realmente existia. Achávamos anteriormente que os critérios abaixo faziam parte desse bug, já que por si só não querem dizer muita coisa.
> > * [ ]  Módulo 5 atividade 8
> > 
> > * [ ]  Módulo 12 atividade 19
> > 
> > * [ ]  Módulo 15 atividade 25
