### ISSUE TITLE
BUGFIX - Mentoria

### ISSUE THREAD

**Issue by gabiMSilva** [fga-eps-mds/2020.1-Grupo4#99]
# BUGFIX - Mentoria

## Descrição

Defeitos e problemas relacionados os fluxos de mentor

## Critérios de Aceitação (se aplicável)

- [x] Botão de aceitar e solicitar do mentor estão redundantes funcionalmente. Se ele está disponível o botão fica redundante. Opções:
   - Adicionar um range de aprendizes que ele deseja aceitar;
   - Deixar só o botão de disponível e remover o de solicitar;
- [ ] Centralizar cards de mentoria, conforme quantidade;
- [x] Aprendiz com curso concluído NÃO deve ter acesso a mentores. Isso também deve ficar claro;
- [x] Mentor não validado NÃO pode ser atribuído a aprendiz algum;
- [x] Após o cancelamento de mentoria, mentor e aprendiz devem estar na blacklist um do outro, e um não pode ser mais atribuído ao outro.

**Comment by Rocsantos** [comment]
O que seria a centralização dos cards de mentoria?
E da forma que foi implementado o aprendiz já não tem acesso a novo mentores.
No caso seria apagar o histórico do mentor que o aluno teve antes de concluir o tutorial?

**Comment by gabiMSilva** [comment]
> O que seria a centralização dos cards de mentoria?
> E da forma que foi implementado o aprendiz já não tem acesso a novo mentores.
> No caso seria apagar o histórico do mentor que o aluno teve antes de concluir o tutorial?

@GeovanaRamos pode te confirmar, mas pelo que entendi, o aprendiz não deve continuar nem adicionar um mentor após concluir o tutorial.

E quando um mentor procurar por um aprendiz, os que já concluíram o curso não devem estar entre as opções.

**Comment by Rocsantos** [comment]
> o aprendiz não deve continuar nem adicionar um mentor após concluir o tutorial.

Eu não cheguei a realizar este teste, mas aparentemente isso já esta implementado, vou verificar direitinho se existe esse bug.

> E quando um mentor procurar por um aprendiz, os que já concluíram o curso não devem estar entre as opções.

Acabei de concertar isso :+1:

**Comment by Rocsantos** [comment]
Meninas, os cards, não estão centralizados? Aparentemente pra mim e para o Pedro estão centralizados.

**Comment by GeovanaRamos** [comment]
> Meninas, os cards, não estão centralizados? Aparentemente pra mim e para o Pedro estão centralizados.

Coloca o print aqui. Pode ser que tenha sido corrigido em outras sprints

**Comment by peHaick** [comment]
![aprendiz](https://user-images.githubusercontent.com/57498006/99836535-03b71500-2b45-11eb-9c58-77f5c87b9395.png)
![mentor](https://user-images.githubusercontent.com/57498006/99836538-06b20580-2b45-11eb-8915-3e9ff9d31d44.png)
